In [2]:
import pandas as pd
import numpy as np
import itertools

In [3]:
data = pd.HDFStore('bdv-data.h5')
print(data.keys())

['/flat', '/gifi']

In [4]:
gifi = data['gifi']
gifi.sort_index(inplace=True)
gby = gifi.groupby(level='year')

In [5]:
def filter_by_list_of_yrs(gifi_df, years=[2011,2012,2013,2014,2015,2016,2017,2018,2019]):
    gby = gifi_df.groupby(level='year')
    bvd_ids = None
    for y in years:
        current_year_bv_ids = set(gby.groups[y].droplevel('year'))
        if bvd_ids == None:
            bvd_ids = current_year_bv_ids
        else:
            bvd_ids = bvd_ids.intersection(current_year_bv_ids)
    tuples = list(itertools.product(bvd_ids,years))
    select_index = pd.MultiIndex.from_tuples(tuples, names=['bv_id','year'])
    rc = gifi_df.loc[select_index]
    rc.sort_index(inplace=True)
    return rc

In [6]:
all9 = filter_by_list_of_yrs(gifi)
all9.head(36)

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114838 2011                               -0.505             -0.505
           2012                               -2.561             -2.561
           2013                                7.658              7.658
           2014                               21.344             21.344
           2015                               61.440             19.280
           2016                               22.798             22.798
           2017                               39.533             39.533
           2018                               44.736             44.736
           2019                               39.009             39.009
GB07114865 2011                               13.830             -6.493
           2012                                9.066            -11.257
           2013                                9.066            -11.257
           2014                                9.066            -11.257
           2015                               36.972              8.915
           2016                              135.507            135.507
           2017                              112.487            112.487
           2018                              120.646            120.646
           2019                               73.569             54.569
GB07114884 2011                                0.002              0.002
           2012                                0.002              0.002
           2013                               -2.995             -2.995
           2014                               -7.265             -7.265
           2015                               64.588              1.101
           2016                               60.029            -13.479
           2017                               27.708            -37.746
           2018                               35.040            -23.566
           2019                               46.494             -5.692
GB07114896 2011                               16.029             -3.136
           2012                               12.939             -2.147
           2013                               -5.465             -9.465
           2014                               -0.361             -3.461
           2015                                7.767             -2.035
           2016                                7.864             -3.578
           2017                                9.764              3.785
           2018                                0.193             -1.952
           2019                                0.193             -1.952

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114838 2011                              -0.505               32.892
           2012                              -2.561               33.273
           2013                               7.658               59.282
           2014                              21.344               66.893
           2015                              61.440               61.440
           2016                              22.798               69.024
           2017                              39.533               53.914
           2018                              44.736               78.849
           2019                              39.009               77.946
GB07114865 2011                              13.830               16.028
           2012                               5.052               10.592
           2013                               5.052               10.592
           2014                               5.052               10.592
           2015                              32.958               36.972
           2016                             135.507              172.596
           2017                             112.487              153.075
           2018                             120.646              160.939
           2019                              73.569              321.872
GB07114884 2011                               0.002                0.002
           2012                               0.002                0.002
           2013                              -2.995               13.902
           2014                              -7.265               35.675
           2015                              64.588               97.494
           2016                              60.029               78.379
           2017                              25.550               39.391
           2018                              33.451               46.890
           2019                              46.494               56.592
GB07114896 2011                              11.029               16.029
           2012                               9.983               23.820
           2013                              -8.421               19.118
           2014                              -3.361               14.276
           2015                               7.767               11.612
           2016                               4.864               10.578
           2017                               6.764                9.764
           2018                               0.193                0.193
           2019                               0.193                0.193

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114838 2011                                       -0.505
           2012                                       -2.561
           2013                                        7.658
           2014                                       16.693
           2015                                       57.417
           2016                                       18.540
           2017                                       34.853
           2018                                       14.023
           2019                                        8.670
GB07114865 2011                                        5.803
           2012                                        5.052
           2013                                        5.052
           2014                                        5.052
           2015                                        5.580
           2016                                      -11.038
           2017                                       31.007
           2018                                      113.731
           2019                                       58.846
GB07114884 2011                                        0.002
           2012                                        0.002
           2013                                       -8.541
           2014                                      -11.988
           2015                                       59.928
           2016                                       39.785
           2017                                       10.420
           2018                                       20.874
           2019                                       34.804
GB07114896 2011                                       11.029
           2012                                        7.951
           2013                                      -11.209
           2014                                       -4.700
           2015                                        3.445
           2016                                        3.631
           2017                                        5.537
           2018                                        0.193
           2019                                        0.193

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114838 2011                     -0.505                 32.892
           2012                     -2.561                 33.273
           2013                      7.658                 59.282
           2014                     21.344                 62.242
           2015                     19.280                 57.417
           2016                     22.798                 64.766
           2017                     39.533                 49.234
           2018                     44.736                 48.136
           2019                     39.009                 47.607
GB07114865 2011                     -6.493                  8.001
           2012                    -11.257                  6.578
           2013                    -11.257                  6.578
           2014                    -11.257                  6.578
           2015                      8.915                  5.580
           2016                    135.507                 26.051
           2017                    112.487                 71.595
           2018                    120.646                154.024
           2019                     54.569                307.149
GB07114884 2011                      0.002                  0.002
           2012                      0.002                  0.002
           2013                     -2.995                  8.356
           2014                     -7.265                 30.952
           2015                      1.101                 92.834
           2016                    -13.479                 58.135
           2017                    -37.746                 22.103
           2018                    -23.566                 32.724
           2019                     -5.692                 44.902
GB07114896 2011                     -3.136                 11.029
           2012                     -2.147                 18.832
           2013                     -9.465                 13.374
           2014                     -3.461                  9.937
           2015                     -2.035                  7.290
           2016                     -3.578                  6.345
           2017                      3.785                  5.537
           2018                     -1.952                  0.193
           2019                     -1.952                  0.193

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114838 2011                 -0.506                     -33.397
           2012                 -2.562                     -35.834
           2013                  7.657                     -51.624
           2014                 21.343                     -45.549
           2015                 19.279                         NaN
           2016                 22.797                     -46.226
           2017                 39.533                     -14.381
           2018                 44.736                     -34.113
           2019                 39.009                     -38.937
GB07114865 2011                 -6.593                      -2.198
           2012                -11.357                      -1.526
           2013                -11.357                      -1.526
           2014                -11.357                      -1.526
           2015                  8.815                         NaN
           2016                135.407                     -37.089
           2017                112.387                     -40.588
           2018                120.546                     -40.293
           2019                 54.569                    -248.303
GB07114884 2011                    NaN                         NaN
           2012                    NaN                         NaN
           2013                 -2.997                     -16.897
           2014                 -7.267                     -42.940
           2015                  1.101                     -32.906
           2016                -13.479                     -18.350
           2017                -37.748                     -11.683
           2018                -23.566                     -11.850
           2019                 -5.692                     -10.098
GB07114896 2011                 -3.136                         NaN
           2012                 -2.147                     -10.881
           2013                 -9.465                     -24.583
           2014                 -3.561                     -14.637
           2015                 -2.035                      -3.845
           2016                 -3.678                      -2.714
           2017                  3.685                         NaN
           2018                 -2.052                         NaN
           2019                 -2.052                         NaN

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114838 2011                         -1.535328  ...                NaN
           2012                         -7.696931  ...                NaN
           2013                         12.917918  ...                NaN
           2014                         31.907673  ...                NaN
           2015                         31.380208  ...                NaN
           2016                         33.029091  ...                NaN
           2017                         73.326038  ...                NaN
           2018                         56.736293  ...                NaN
           2019                         50.046186  ...                NaN
GB07114865 2011                        -40.510357  ...                NaN
           2012                               NaN  ...                NaN
           2013                               NaN  ...                NaN
           2014                               NaN  ...                NaN
           2015                         24.112842  ...                NaN
           2016                         78.511089  ...                NaN
           2017                         73.484893  ...                NaN
           2018                         74.963806  ...                NaN
           2019                         16.953634  ...                NaN
GB07114884 2011                        100.000000  ...                NaN
           2012                        100.000000  ...                NaN
           2013                        -21.543663  ...                NaN
           2014                        -20.364401  ...                NaN
           2015                          1.129300  ...                NaN
           2016                        -17.197208  ...                NaN
           2017                        -95.823919  ...                NaN
           2018                        -50.258051  ...                NaN
           2019                        -10.057959  ...                NaN
GB07114896 2011                        -19.564539  ...                NaN
           2012                         -9.013434  ...                NaN
           2013                        -49.508317  ...                NaN
           2014                        -24.243486  ...                NaN
           2015                        -17.524974  ...                NaN
           2016                        -33.824920  ...                NaN
           2017                         38.764850  ...                NaN
           2018                               NaN  ...                NaN
           2019                               NaN  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114838 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN
GB07114865 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN
GB07114884 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN
GB07114896 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114838 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN
GB07114865 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN
GB07114884 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN
GB07114896 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114838 2011                         NaN                             NaN
           2012                         NaN                             NaN

In [7]:
two = filter_by_list_of_yrs(gifi, [2011,2012])
print(two.shape)
two.head(36)

(41986, 177)

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114772 2011                                0.313              0.313
           2012                                0.313              0.313
GB07114798 2011                               -0.436             -0.436
           2012                               -1.253             -1.253
GB07114838 2011                               -0.505             -0.505
           2012                               -2.561             -2.561
GB07114865 2011                               13.830             -6.493
           2012                                9.066            -11.257
GB07114872 2011                                0.189              0.189
           2012                                1.276              1.276
GB07114884 2011                                0.002              0.002
           2012                                0.002              0.002
GB07114896 2011                               16.029             -3.136
           2012                               12.939             -2.147
GB07114903 2011                              -48.507            -48.507
           2012                              -16.418            -16.418
GB07114911 2011                                1.622              1.622
           2012                                3.472              3.472
GB07114945 2011                              -30.529            -30.529
           2012                              -13.654            -13.654
GB07114946 2011                               -0.264             -0.264
           2012                                0.763              0.763
GB07114950 2011                               -2.407             -2.407
           2012                                3.431              3.431
GB07114956 2011                                0.111              0.111
           2012                                0.111              0.111
GB07114959 2011                                0.891              0.891
           2012                                2.813              2.813
GB07114962 2011                               -2.376             -2.376
           2012                                1.620              1.620
GB07114966 2011                                0.001              0.001
           2012                                0.001              0.001
GB07114969 2011                                1.779              1.779
           2012                               14.133             14.133
GB07114981 2011                               -0.131             -0.131
           2012                               -0.178             -0.178

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114772 2011                               0.313               24.788
           2012                               0.313                0.313
GB07114798 2011                              -0.436                0.100
           2012                              -1.253                0.100
GB07114838 2011                              -0.505               32.892
           2012                              -2.561               33.273
GB07114865 2011                              13.830               16.028
           2012                               5.052               10.592
GB07114872 2011                               0.189                8.260
           2012                               1.276                6.618
GB07114884 2011                               0.002                0.002
           2012                               0.002                0.002
GB07114896 2011                              11.029               16.029
           2012                               9.983               23.820
GB07114903 2011                             -48.507               70.674
           2012                             -16.418               94.014
GB07114911 2011                               1.622                6.672
           2012                               3.472               13.341
GB07114945 2011                             -30.529              260.407
           2012                             -13.654              170.864
GB07114946 2011                              -0.264                  NaN
           2012                               0.763                0.769
GB07114950 2011                              -2.407                  NaN
           2012                               3.431                3.431
GB07114956 2011                               0.111               16.675
           2012                               0.111                0.416
GB07114959 2011                               0.891                0.891
           2012                               2.813                2.813
GB07114962 2011                              -2.376                2.516
           2012                               1.620               11.172
GB07114966 2011                               0.001                3.514
           2012                               0.001                0.001
GB07114969 2011                               1.779               15.117
           2012                              14.133               31.173
GB07114981 2011                              -0.131                0.120
           2012                              -0.178                0.323

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114772 2011                                        0.313
           2012                                        0.313
GB07114798 2011                                       -0.436
           2012                                       -1.253
GB07114838 2011                                       -0.505
           2012                                       -2.561
GB07114865 2011                                        5.803
           2012                                        5.052
GB07114872 2011                                       -2.308
           2012                                       -0.609
GB07114884 2011                                        0.002
           2012                                        0.002
GB07114896 2011                                       11.029
           2012                                        7.951
GB07114903 2011                                      -48.507
           2012                                      -16.418
GB07114911 2011                                        1.622
           2012                                        3.472
GB07114945 2011                                      -30.529
           2012                                      -13.654
GB07114946 2011                                       -0.264
           2012                                        0.763
GB07114950 2011                                       -2.407
           2012                                        3.431
GB07114956 2011                                       -0.305
           2012                                       -0.305
GB07114959 2011                                        0.891
           2012                                        2.813
GB07114962 2011                                       -2.659
           2012                                        1.478
GB07114966 2011                                        0.001
           2012                                        0.001
GB07114969 2011                                        1.779
           2012                                       14.133
GB07114981 2011                                       -0.131
           2012                                       -0.178

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114772 2011                      0.313                 24.788
           2012                      0.313                  0.313
GB07114798 2011                     -0.436                  0.100
           2012                     -1.253                  0.100
GB07114838 2011                     -0.505                 32.892
           2012                     -2.561                 33.273
GB07114865 2011                     -6.493                  8.001
           2012                    -11.257                  6.578
GB07114872 2011                      0.189                  5.763
           2012                      1.276                  4.733
GB07114884 2011                      0.002                  0.002
           2012                      0.002                  0.002
GB07114896 2011                     -3.136                 11.029
           2012                     -2.147                 18.832
GB07114903 2011                    -48.507                 70.674
           2012                    -16.418                 94.014
GB07114911 2011                      1.622                  6.672
           2012                      3.472                 13.341
GB07114945 2011                    -30.529                260.407
           2012                    -13.654                170.864
GB07114946 2011                     -0.264                    NaN
           2012                      0.763                  0.769
GB07114950 2011                     -2.407                    NaN
           2012                      3.431                  3.431
GB07114956 2011                      0.111                 16.259
           2012                      0.111                    NaN
GB07114959 2011                      0.891                  0.891
           2012                      2.813                  2.813
GB07114962 2011                     -2.376                  2.233
           2012                      1.620                 11.030
GB07114966 2011                      0.001                  3.514
           2012                      0.001                  0.001
GB07114969 2011                      1.779                 15.117
           2012                     14.133                 31.173
GB07114981 2011                     -0.131                  0.120
           2012                     -0.178                  0.323

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114772 2011                  0.311                     -24.475
           2012                  0.311                         NaN
GB07114798 2011                 -0.536                      -0.536
           2012                 -1.353                      -1.353
GB07114838 2011                 -0.506                     -33.397
           2012                 -2.562                     -35.834
GB07114865 2011                 -6.593                      -2.198
           2012                -11.357                      -1.526
GB07114872 2011                  0.089                      -8.071
           2012                  1.176                      -5.342
GB07114884 2011                    NaN                         NaN
           2012                    NaN                         NaN
GB07114896 2011                 -3.136                         NaN
           2012                 -2.147                     -10.881
GB07114903 2011                -48.507                    -119.181
           2012                -16.418                    -110.432
GB07114911 2011                  1.622                      -5.050
           2012                  3.472                      -9.869
GB07114945 2011                -30.530                    -290.936
           2012                -13.655                    -184.518
GB07114946 2011                 -0.264                      -0.264
           2012                  0.663                      -0.006
GB07114950 2011                 -2.407                      -2.407
           2012                  3.431                         NaN
GB07114956 2011                  0.011                     -16.564
           2012                  0.011                      -0.305
GB07114959 2011                  0.891                         NaN
           2012                  2.813                         NaN
GB07114962 2011                 -2.386                      -4.892
           2012                  1.610                      -9.552
GB07114966 2011                    NaN                      -3.513
           2012                    NaN                         NaN
GB07114969 2011                  1.778                     -13.338
           2012                 14.132                     -17.040
GB07114981 2011                 -0.131                      -0.251
           2012                 -0.178                      -0.501

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114772 2011                          1.262708  ...                NaN
           2012                        100.000000  ...                NaN
GB07114798 2011                               NaN  ...                NaN
           2012                               NaN  ...                NaN
GB07114838 2011                         -1.535328  ...                NaN
           2012                         -7.696931  ...                NaN
GB07114865 2011                        -40.510357  ...                NaN
           2012                               NaN  ...                NaN
GB07114872 2011                          2.288136  ...                NaN
           2012                         19.280749  ...                NaN
GB07114884 2011                        100.000000  ...                NaN
           2012                        100.000000  ...                NaN
GB07114896 2011                        -19.564539  ...                NaN
           2012                         -9.013434  ...                NaN
GB07114903 2011                        -68.634859  ...                NaN
           2012                        -17.463357  ...                NaN
GB07114911 2011                         24.310552  ...                NaN
           2012                         26.025036  ...                NaN
GB07114945 2011                        -11.723571  ...                NaN
           2012                         -7.991151  ...                NaN
GB07114946 2011                               NaN  ...                NaN
           2012                         99.219766  ...                NaN
GB07114950 2011                               NaN  ...                NaN
           2012                        100.000000  ...                NaN
GB07114956 2011                          0.665667  ...                NaN
           2012                         26.682692  ...                NaN
GB07114959 2011                        100.000000  ...                NaN
           2012                        100.000000  ...                NaN
GB07114962 2011                        -94.435612  ...                NaN
           2012                         14.500537  ...                NaN
GB07114966 2011                          0.028458  ...                NaN
           2012                        100.000000  ...                NaN
GB07114969 2011                         11.768208  ...                NaN
           2012                         45.337311  ...                NaN
GB07114981 2011                               NaN  ...                NaN
           2012                        -55.108359  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114772 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114798 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114838 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114865 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114872 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114884 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114896 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114903 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114911 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114945 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114946 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114950 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114956 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114959 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114962 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114966 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114969 2011               NaN                       NaN
           2012               NaN                       NaN
GB07114981 2011               NaN                       NaN
           2012               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114772 2011                                    NaN
           2012                                    NaN
GB07114798 2011                                    NaN
           2012                                    NaN
GB07114838 2011                                    NaN
           2012                                    NaN
GB07114865 2011                                    NaN
           2012                                    NaN
GB07114872 2011                                    NaN
           2012                                    NaN
GB07114884 2011                                    NaN
           2012                                    NaN
GB07114896 2011                                    NaN
           2012                                    NaN
GB07114903 2011                                    NaN
           2012                                    NaN
GB07114911 2011                                    NaN
           2012                                    NaN
GB07114945 2011                                    NaN
           2012                                    NaN
GB07114946 2011                                    NaN
           2012                                    NaN
GB07114950 2011                                    NaN
           2012                                    NaN
GB07114956 2011                                    NaN
           2012                                    NaN
GB07114959 2011                                    NaN
           2012                                    NaN
GB07114962 2011                                    NaN
           2012                                    NaN
GB07114966 2011                                    NaN
           2012                                    NaN
GB07114969 2011                                    NaN
           2012                                    NaN
GB07114981 2011                                    NaN
           2012                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114772 2011                         NaN                             NaN
           2012                         NaN                             NaN

In [8]:
_four = filter_by_list_of_yrs(gifi, [2015,2016,2017,2018])
print(_four.shape)
_four.head(36)

(300760, 177)

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114798 2015                               -2.761             -2.761
           2016                               -2.761             -2.761
           2017                                0.100              0.100
           2018                                0.100              0.100
GB07114838 2015                               61.440             19.280
           2016                               22.798             22.798
           2017                               39.533             39.533
           2018                               44.736             44.736
GB07114865 2015                               36.972              8.915
           2016                              135.507            135.507
           2017                              112.487            112.487
           2018                              120.646            120.646
GB07114884 2015                               64.588              1.101
           2016                               60.029            -13.479
           2017                               27.708            -37.746
           2018                               35.040            -23.566
GB07114896 2015                                7.767             -2.035
           2016                                7.864             -3.578
           2017                                9.764              3.785
           2018                                0.193             -1.952
GB07114903 2015                               36.047             36.047
           2016                               47.272             47.272
           2017                              126.303            126.303
           2018                              187.258            187.258
GB07114911 2015                                1.000              1.000
           2016                                4.475              4.475
           2017                                7.733              7.733
           2018                                8.432              8.432
GB07114945 2015                               15.000             15.000
           2016                               15.000             15.000
           2017                               16.000             16.000
           2018                               66.000             66.000
GB07114950 2015                               14.944             14.944
           2016                               16.109             16.109
           2017                               15.832             15.832
           2018                               11.180             11.180

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114798 2015                              -2.761                0.100
           2016                              -2.761                0.100
           2017                               0.100                0.100
           2018                               0.100                0.100
GB07114838 2015                              61.440               61.440
           2016                              22.798               69.024
           2017                              39.533               53.914
           2018                              44.736               78.849
GB07114865 2015                              32.958               36.972
           2016                             135.507              172.596
           2017                             112.487              153.075
           2018                             120.646              160.939
GB07114884 2015                              64.588               97.494
           2016                              60.029               78.379
           2017                              25.550               39.391
           2018                              33.451               46.890
GB07114896 2015                               7.767               11.612
           2016                               4.864               10.578
           2017                               6.764                9.764
           2018                               0.193                0.193
GB07114903 2015                              36.047              165.557
           2016                              47.272              672.520
           2017                             126.303              945.266
           2018                             187.258              955.807
GB07114911 2015                               1.000                1.250
           2016                               4.475                4.925
           2017                               7.733                8.033
           2018                               8.432                8.792
GB07114945 2015                              15.000              220.000
           2016                              15.000              220.000
           2017                              16.000              415.000
           2018                              66.000               87.000
GB07114950 2015                              14.944               14.944
           2016                              16.109               16.109
           2017                              15.832               15.832
           2018                              11.180               11.180

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114798 2015                                       -2.761
           2016                                       -2.761
           2017                                        0.100
           2018                                        0.100
GB07114838 2015                                       57.417
           2016                                       18.540
           2017                                       34.853
           2018                                       14.023
GB07114865 2015                                        5.580
           2016                                      -11.038
           2017                                       31.007
           2018                                      113.731
GB07114884 2015                                       59.928
           2016                                       39.785
           2017                                       10.420
           2018                                       20.874
GB07114896 2015                                        3.445
           2016                                        3.631
           2017                                        5.537
           2018                                        0.193
GB07114903 2015                                       35.336
           2016                                       42.400
           2017                                      105.800
           2018                                      179.325
GB07114911 2015                                        1.000
           2016                                        4.475
           2017                                        7.733
           2018                                        8.432
GB07114945 2015                                       15.000
           2016                                       15.000
           2017                                       16.000
           2018                                       66.000
GB07114950 2015                                       14.944
           2016                                       16.109
           2017                                       15.832
           2018                                       11.180

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114798 2015                     -2.761                  0.100
           2016                     -2.761                  0.100
           2017                      0.100                  0.100
           2018                      0.100                  0.100
GB07114838 2015                     19.280                 57.417
           2016                     22.798                 64.766
           2017                     39.533                 49.234
           2018                     44.736                 48.136
GB07114865 2015                      8.915                  5.580
           2016                    135.507                 26.051
           2017                    112.487                 71.595
           2018                    120.646                154.024
GB07114884 2015                      1.101                 92.834
           2016                    -13.479                 58.135
           2017                    -37.746                 22.103
           2018                    -23.566                 32.724
GB07114896 2015                     -2.035                  7.290
           2016                     -3.578                  6.345
           2017                      3.785                  5.537
           2018                     -1.952                  0.193
GB07114903 2015                     36.047                164.846
           2016                     47.272                667.648
           2017                    126.303                924.763
           2018                    187.258                947.874
GB07114911 2015                      1.000                  1.250
           2016                      4.475                  4.925
           2017                      7.733                  8.033
           2018                      8.432                  8.792
GB07114945 2015                     15.000                220.000
           2016                     15.000                220.000
           2017                     16.000                415.000
           2018                     66.000                 87.000
GB07114950 2015                     14.944                 14.944
           2016                     16.109                 16.109
           2017                     15.832                 15.832
           2018                     11.180                 11.180

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114798 2015                 -2.761                      -2.861
           2016                 -2.761                      -2.861
           2017                  0.100                         NaN
           2018                  0.100                         NaN
GB07114838 2015                 19.279                         NaN
           2016                 22.797                     -46.226
           2017                 39.533                     -14.381
           2018                 44.736                     -34.113
GB07114865 2015                  8.815                         NaN
           2016                135.407                     -37.089
           2017                112.387                     -40.588
           2018                120.546                     -40.293
GB07114884 2015                  1.101                     -32.906
           2016                -13.479                     -18.350
           2017                -37.748                     -11.683
           2018                -23.566                     -11.850
GB07114896 2015                 -2.035                      -3.845
           2016                 -3.678                      -2.714
           2017                  3.685                         NaN
           2018                 -2.052                         NaN
GB07114903 2015                 36.047                    -129.510
           2016                 47.272                    -625.248
           2017                126.303                    -818.963
           2018                187.258                    -768.549
GB07114911 2015                  1.000                      -0.250
           2016                  4.475                      -0.450
           2017                  7.733                      -0.300
           2018                  8.432                      -0.360
GB07114945 2015                 15.000                    -205.000
           2016                 15.000                    -205.000
           2017                 16.000                    -399.000
           2018                 66.000                     -21.000
GB07114950 2015                 14.944                         NaN
           2016                 16.109                         NaN
           2017                 15.832                         NaN
           2018                 11.180                         NaN

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114798 2015                               NaN  ...                NaN
           2016                               NaN  ...                NaN
           2017                        100.000000  ...                NaN
           2018                        100.000000  ...                NaN
GB07114838 2015                         31.380208  ...                NaN
           2016                         33.029091  ...                NaN
           2017                         73.326038  ...                NaN
           2018                         56.736293  ...                NaN
GB07114865 2015                         24.112842  ...                NaN
           2016                         78.511089  ...                NaN
           2017                         73.484893  ...                NaN
           2018                         74.963806  ...                NaN
GB07114884 2015                          1.129300  ...                NaN
           2016                        -17.197208  ...                NaN
           2017                        -95.823919  ...                NaN
           2018                        -50.258051  ...                NaN
GB07114896 2015                        -17.524974  ...                NaN
           2016                        -33.824920  ...                NaN
           2017                         38.764850  ...                NaN
           2018                               NaN  ...                NaN
GB07114903 2015                         21.773166  ...                NaN
           2016                          7.029085  ...                NaN
           2017                         13.361636  ...                NaN
           2018                         19.591612  ...                NaN
GB07114911 2015                         80.000000  ...                NaN
           2016                         90.862944  ...                NaN
           2017                         96.265405  ...                NaN
           2018                         95.905369  ...                NaN
GB07114945 2015                          6.818182  ...                NaN
           2016                          6.818182  ...                NaN
           2017                          3.855422  ...                NaN
           2018                         75.862069  ...                NaN
GB07114950 2015                        100.000000  ...                NaN
           2016                        100.000000  ...                NaN
           2017                        100.000000  ...                NaN
           2018                        100.000000  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114798 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114838 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114865 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114884 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114896 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114903 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114911 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114945 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114950 2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114798 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114838 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114865 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114884 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114896 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114903 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114911 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114945 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114950 2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114798 2015                         NaN                             NaN
           2016                         NaN                             NaN

In [9]:
_four = filter_by_list_of_yrs(gifi, [2012,2014,2016,2018])
print(_four.shape)
_four.head(36)

(116876, 177)

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114798 2012                               -1.253             -1.253
           2014                               -2.761             -2.761
           2016                               -2.761             -2.761
           2018                                0.100              0.100
GB07114838 2012                               -2.561             -2.561
           2014                               21.344             21.344
           2016                               22.798             22.798
           2018                               44.736             44.736
GB07114865 2012                                9.066            -11.257
           2014                                9.066            -11.257
           2016                              135.507            135.507
           2018                              120.646            120.646
GB07114884 2012                                0.002              0.002
           2014                               -7.265             -7.265
           2016                               60.029            -13.479
           2018                               35.040            -23.566
GB07114896 2012                               12.939             -2.147
           2014                               -0.361             -3.461
           2016                                7.864             -3.578
           2018                                0.193             -1.952
GB07114903 2012                              -16.418            -16.418
           2014                               29.402             29.402
           2016                               47.272             47.272
           2018                              187.258            187.258
GB07114911 2012                                3.472              3.472
           2014                                2.946              2.946
           2016                                4.475              4.475
           2018                                8.432              8.432
GB07114945 2012                              -13.654            -13.654
           2014                               15.000             15.000
           2016                               15.000             15.000
           2018                               66.000             66.000
GB07114950 2012                                3.431              3.431
           2014                                7.962              7.962
           2016                               16.109             16.109
           2018                               11.180             11.180

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114798 2012                              -1.253                0.100
           2014                              -2.761                0.100
           2016                              -2.761                0.100
           2018                               0.100                0.100
GB07114838 2012                              -2.561               33.273
           2014                              21.344               66.893
           2016                              22.798               69.024
           2018                              44.736               78.849
GB07114865 2012                               5.052               10.592
           2014                               5.052               10.592
           2016                             135.507              172.596
           2018                             120.646              160.939
GB07114884 2012                               0.002                0.002
           2014                              -7.265               35.675
           2016                              60.029               78.379
           2018                              33.451               46.890
GB07114896 2012                               9.983               23.820
           2014                              -3.361               14.276
           2016                               4.864               10.578
           2018                               0.193                0.193
GB07114903 2012                             -16.418               94.014
           2014                              29.402              186.948
           2016                              47.272              672.520
           2018                             187.258              955.807
GB07114911 2012                               3.472               13.341
           2014                               2.946                3.271
           2016                               4.475                4.925
           2018                               8.432                8.792
GB07114945 2012                             -13.654              170.864
           2014                              15.000              220.000
           2016                              15.000              220.000
           2018                              66.000               87.000
GB07114950 2012                               3.431                3.431
           2014                               7.962                7.962
           2016                              16.109               16.109
           2018                              11.180               11.180

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114798 2012                                       -1.253
           2014                                       -2.761
           2016                                       -2.761
           2018                                        0.100
GB07114838 2012                                       -2.561
           2014                                       16.693
           2016                                       18.540
           2018                                       14.023
GB07114865 2012                                        5.052
           2014                                        5.052
           2016                                      -11.038
           2018                                      113.731
GB07114884 2012                                        0.002
           2014                                      -11.988
           2016                                       39.785
           2018                                       20.874
GB07114896 2012                                        7.951
           2014                                       -4.700
           2016                                        3.631
           2018                                        0.193
GB07114903 2012                                      -16.418
           2014                                       28.453
           2016                                       42.400
           2018                                      179.325
GB07114911 2012                                        3.472
           2014                                        2.946
           2016                                        4.475
           2018                                        8.432
GB07114945 2012                                      -13.654
           2014                                       15.000
           2016                                       15.000
           2018                                       66.000
GB07114950 2012                                        3.431
           2014                                        7.962
           2016                                       16.109
           2018                                       11.180

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114798 2012                     -1.253                  0.100
           2014                     -2.761                  0.100
           2016                     -2.761                  0.100
           2018                      0.100                  0.100
GB07114838 2012                     -2.561                 33.273
           2014                     21.344                 62.242
           2016                     22.798                 64.766
           2018                     44.736                 48.136
GB07114865 2012                    -11.257                  6.578
           2014                    -11.257                  6.578
           2016                    135.507                 26.051
           2018                    120.646                154.024
GB07114884 2012                      0.002                  0.002
           2014                     -7.265                 30.952
           2016                    -13.479                 58.135
           2018                    -23.566                 32.724
GB07114896 2012                     -2.147                 18.832
           2014                     -3.461                  9.937
           2016                     -3.578                  6.345
           2018                     -1.952                  0.193
GB07114903 2012                    -16.418                 94.014
           2014                     29.402                185.999
           2016                     47.272                667.648
           2018                    187.258                947.874
GB07114911 2012                      3.472                 13.341
           2014                      2.946                  3.271
           2016                      4.475                  4.925
           2018                      8.432                  8.792
GB07114945 2012                    -13.654                170.864
           2014                     15.000                220.000
           2016                     15.000                220.000
           2018                     66.000                 87.000
GB07114950 2012                      3.431                  3.431
           2014                      7.962                  7.962
           2016                     16.109                 16.109
           2018                     11.180                 11.180

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114798 2012                 -1.353                      -1.353
           2014                 -2.861                      -2.861
           2016                 -2.761                      -2.861
           2018                  0.100                         NaN
GB07114838 2012                 -2.562                     -35.834
           2014                 21.343                     -45.549
           2016                 22.797                     -46.226
           2018                 44.736                     -34.113
GB07114865 2012                -11.357                      -1.526
           2014                -11.357                      -1.526
           2016                135.407                     -37.089
           2018                120.546                     -40.293
GB07114884 2012                    NaN                         NaN
           2014                 -7.267                     -42.940
           2016                -13.479                     -18.350
           2018                -23.566                     -11.850
GB07114896 2012                 -2.147                     -10.881
           2014                 -3.561                     -14.637
           2016                 -3.678                      -2.714
           2018                 -2.052                         NaN
GB07114903 2012                -16.418                    -110.432
           2014                 29.402                    -157.546
           2016                 47.272                    -625.248
           2018                187.258                    -768.549
GB07114911 2012                  3.472                      -9.869
           2014                  2.946                      -0.325
           2016                  4.475                      -0.450
           2018                  8.432                      -0.360
GB07114945 2012                -13.655                    -184.518
           2014                 15.000                    -205.000
           2016                 15.000                    -205.000
           2018                 66.000                     -21.000
GB07114950 2012                  3.431                         NaN
           2014                  7.962                         NaN
           2016                 16.109                         NaN
           2018                 11.180                         NaN

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114798 2012                               NaN  ...                NaN
           2014                               NaN  ...                NaN
           2016                               NaN  ...                NaN
           2018                        100.000000  ...                NaN
GB07114838 2012                         -7.696931  ...                NaN
           2014                         31.907673  ...                NaN
           2016                         33.029091  ...                NaN
           2018                         56.736293  ...                NaN
GB07114865 2012                               NaN  ...                NaN
           2014                               NaN  ...                NaN
           2016                         78.511089  ...                NaN
           2018                         74.963806  ...                NaN
GB07114884 2012                        100.000000  ...                NaN
           2014                        -20.364401  ...                NaN
           2016                        -17.197208  ...                NaN
           2018                        -50.258051  ...                NaN
GB07114896 2012                         -9.013434  ...                NaN
           2014                        -24.243486  ...                NaN
           2016                        -33.824920  ...                NaN
           2018                               NaN  ...                NaN
GB07114903 2012                        -17.463357  ...                NaN
           2014                         15.727368  ...                NaN
           2016                          7.029085  ...                NaN
           2018                         19.591612  ...                NaN
GB07114911 2012                         26.025036  ...                NaN
           2014                         90.064201  ...                NaN
           2016                         90.862944  ...                NaN
           2018                         95.905369  ...                NaN
GB07114945 2012                         -7.991151  ...                NaN
           2014                          6.818182  ...                NaN
           2016                          6.818182  ...                NaN
           2018                         75.862069  ...                NaN
GB07114950 2012                        100.000000  ...                NaN
           2014                        100.000000  ...                NaN
           2016                        100.000000  ...                NaN
           2018                        100.000000  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114798 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114838 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114865 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114884 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114896 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114903 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114911 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114945 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN
GB07114950 2012               NaN                       NaN
           2014               NaN                       NaN
           2016               NaN                       NaN
           2018               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114798 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114838 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114865 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114884 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114896 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114903 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114911 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114945 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN
GB07114950 2012                                    NaN
           2014                                    NaN
           2016                                    NaN
           2018                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114798 2012                         NaN                             NaN
           2014                         NaN                             NaN