In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.HDFStore('bdv-data.h5')
print(data.keys())

['/flat', '/gifi']

In [4]:

print(data['flat'].shape)
print(data['gifi'].shape)

(125990, 1703)
(677268, 177)

In [5]:
gifi = data['gifi']
gifi.sort_index(inplace=True)
gifi.head(32)

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114772 2011                                0.313              0.313
           2012                                0.313              0.313
           2013                                0.313              0.313
           2014                                0.313              0.313
           2015                                0.313              0.313
           2016                                0.313              0.313
GB07114798 2011                               -0.436             -0.436
           2012                               -1.253             -1.253
           2013                               -2.905             -2.905
           2014                               -2.761             -2.761
           2015                               -2.761             -2.761
           2016                               -2.761             -2.761
           2017                                0.100              0.100
           2018                                0.100              0.100
GB07114838 2011                               -0.505             -0.505
           2012                               -2.561             -2.561
           2013                                7.658              7.658
           2014                               21.344             21.344
           2015                               61.440             19.280
           2016                               22.798             22.798
           2017                               39.533             39.533
           2018                               44.736             44.736
           2019                               39.009             39.009
GB07114865 2011                               13.830             -6.493
           2012                                9.066            -11.257
           2013                                9.066            -11.257
           2014                                9.066            -11.257
           2015                               36.972              8.915
           2016                              135.507            135.507
           2017                              112.487            112.487
           2018                              120.646            120.646
           2019                               73.569             54.569

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114772 2011                               0.313               24.788
           2012                               0.313                0.313
           2013                               0.313                0.313
           2014                               0.313                0.313
           2015                               0.313                0.313
           2016                               0.313                0.313
GB07114798 2011                              -0.436                0.100
           2012                              -1.253                0.100
           2013                              -2.905                0.100
           2014                              -2.761                0.100
           2015                              -2.761                0.100
           2016                              -2.761                0.100
           2017                               0.100                0.100
           2018                               0.100                0.100
GB07114838 2011                              -0.505               32.892
           2012                              -2.561               33.273
           2013                               7.658               59.282
           2014                              21.344               66.893
           2015                              61.440               61.440
           2016                              22.798               69.024
           2017                              39.533               53.914
           2018                              44.736               78.849
           2019                              39.009               77.946
GB07114865 2011                              13.830               16.028
           2012                               5.052               10.592
           2013                               5.052               10.592
           2014                               5.052               10.592
           2015                              32.958               36.972
           2016                             135.507              172.596
           2017                             112.487              153.075
           2018                             120.646              160.939
           2019                              73.569              321.872

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114772 2011                                        0.313
           2012                                        0.313
           2013                                        0.313
           2014                                        0.313
           2015                                        0.313
           2016                                        0.313
GB07114798 2011                                       -0.436
           2012                                       -1.253
           2013                                       -2.905
           2014                                       -2.761
           2015                                       -2.761
           2016                                       -2.761
           2017                                        0.100
           2018                                        0.100
GB07114838 2011                                       -0.505
           2012                                       -2.561
           2013                                        7.658
           2014                                       16.693
           2015                                       57.417
           2016                                       18.540
           2017                                       34.853
           2018                                       14.023
           2019                                        8.670
GB07114865 2011                                        5.803
           2012                                        5.052
           2013                                        5.052
           2014                                        5.052
           2015                                        5.580
           2016                                      -11.038
           2017                                       31.007
           2018                                      113.731
           2019                                       58.846

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114772 2011                      0.313                 24.788
           2012                      0.313                  0.313
           2013                      0.313                  0.313
           2014                      0.313                  0.313
           2015                      0.313                  0.313
           2016                      0.313                  0.313
GB07114798 2011                     -0.436                  0.100
           2012                     -1.253                  0.100
           2013                     -2.905                  0.100
           2014                     -2.761                  0.100
           2015                     -2.761                  0.100
           2016                     -2.761                  0.100
           2017                      0.100                  0.100
           2018                      0.100                  0.100
GB07114838 2011                     -0.505                 32.892
           2012                     -2.561                 33.273
           2013                      7.658                 59.282
           2014                     21.344                 62.242
           2015                     19.280                 57.417
           2016                     22.798                 64.766
           2017                     39.533                 49.234
           2018                     44.736                 48.136
           2019                     39.009                 47.607
GB07114865 2011                     -6.493                  8.001
           2012                    -11.257                  6.578
           2013                    -11.257                  6.578
           2014                    -11.257                  6.578
           2015                      8.915                  5.580
           2016                    135.507                 26.051
           2017                    112.487                 71.595
           2018                    120.646                154.024
           2019                     54.569                307.149

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114772 2011                  0.311                     -24.475
           2012                  0.311                         NaN
           2013                  0.311                         NaN
           2014                  0.311                         NaN
           2015                  0.313                         NaN
           2016                  0.313                         NaN
GB07114798 2011                 -0.536                      -0.536
           2012                 -1.353                      -1.353
           2013                 -3.005                      -3.005
           2014                 -2.861                      -2.861
           2015                 -2.761                      -2.861
           2016                 -2.761                      -2.861
           2017                  0.100                         NaN
           2018                  0.100                         NaN
GB07114838 2011                 -0.506                     -33.397
           2012                 -2.562                     -35.834
           2013                  7.657                     -51.624
           2014                 21.343                     -45.549
           2015                 19.279                         NaN
           2016                 22.797                     -46.226
           2017                 39.533                     -14.381
           2018                 44.736                     -34.113
           2019                 39.009                     -38.937
GB07114865 2011                 -6.593                      -2.198
           2012                -11.357                      -1.526
           2013                -11.357                      -1.526
           2014                -11.357                      -1.526
           2015                  8.815                         NaN
           2016                135.407                     -37.089
           2017                112.387                     -40.588
           2018                120.546                     -40.293
           2019                 54.569                    -248.303

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114772 2011                          1.262708  ...                NaN
           2012                        100.000000  ...                NaN
           2013                        100.000000  ...                NaN
           2014                        100.000000  ...                NaN
           2015                        100.000000  ...                NaN
           2016                        100.000000  ...                NaN
GB07114798 2011                               NaN  ...                NaN
           2012                               NaN  ...                NaN
           2013                               NaN  ...                NaN
           2014                               NaN  ...                NaN
           2015                               NaN  ...                NaN
           2016                               NaN  ...                NaN
           2017                        100.000000  ...                NaN
           2018                        100.000000  ...                NaN
GB07114838 2011                         -1.535328  ...                NaN
           2012                         -7.696931  ...                NaN
           2013                         12.917918  ...                NaN
           2014                         31.907673  ...                NaN
           2015                         31.380208  ...                NaN
           2016                         33.029091  ...                NaN
           2017                         73.326038  ...                NaN
           2018                         56.736293  ...                NaN
           2019                         50.046186  ...                NaN
GB07114865 2011                        -40.510357  ...                NaN
           2012                               NaN  ...                NaN
           2013                               NaN  ...                NaN
           2014                               NaN  ...                NaN
           2015                         24.112842  ...                NaN
           2016                         78.511089  ...                NaN
           2017                         73.484893  ...                NaN
           2018                         74.963806  ...                NaN
           2019                         16.953634  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114772 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
GB07114798 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
GB07114838 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN
GB07114865 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114772 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
GB07114798 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
GB07114838 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN
GB07114865 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114772 2011                         NaN                             NaN
           2012                         NaN                             NaN
           2013                         NaN                             NaN
           2014                         NaN                             NaN
           2015                         NaN                             NaN
           2016                         NaN                             NaN
GB07114798 2011                         NaN                             NaN
           2012                         NaN                             NaN
           2013                         NaN                             NaN
           2014                         NaN                             NaN
           2015                         NaN                             NaN
           2016                         NaN                             NaN
           2017                         NaN                             NaN
           2018                         NaN                             NaN
GB07114838 2011                         NaN                             NaN
           2012                         NaN                             NaN
           2013                         NaN                             NaN
           2014                         NaN                             NaN
           2015                         NaN                             NaN
           2016                         NaN                             NaN
           2017                         NaN                             NaN
           2018                         NaN                             NaN
           2019                         NaN                             NaN
GB07114865 2011                         NaN                             NaN
           2012                         NaN                             NaN
           2013                         NaN                             NaN
           2014                         NaN                             NaN
           2015                         NaN                             NaN
           2016                         NaN                             NaN
           2017                         NaN                             NaN

In [6]:
gby = gifi.groupby(level='year')
gby.groups

{2011: MultiIndex([('GB07114772', 2011),
             ('GB07114798', 2011),
             ('GB07114838', 2011),
             ('GB07114865', 2011),
             ('GB07114872', 2011),
             ('GB07114884', 2011),
             ('GB07114896', 2011),
             ('GB07114903', 2011),
             ('GB07114911', 2011),
             ('GB07114945', 2011),
             ...
             (  'IE504084', 2011),
             (  'IE504281', 2011),
             (  'IE504446', 2011),
             (  'IE505087', 2011),
             (  'IE505678', 2011),
             (  'IE505900', 2011),
             (  'IE507305', 2011),
             (  'IE507559', 2011),
             (  'IE508846', 2011),
             (  'IE518146', 2011)],
            names=['bv_id', 'year'], length=21308),
 2012: MultiIndex([('GB07114772', 2012),
             ('GB07114798', 2012),
             ('GB07114838', 2012),
             ('GB07114865', 2012),
             ('GB07114872', 2012),
             ('GB07114884', 2012),
             ('GB07114896', 2012),
             ('GB07114903', 2012),
             ('GB07114911', 2012),
             ('GB07114945', 2012),
             ...
             (  'IE518693', 2012),
             (  'IE518760', 2012),
             (  'IE518936', 2012),
             (  'IE519003', 2012),
             (  'IE519427', 2012),
             (  'IE520017', 2012),
             (  'IE520223', 2012),
             (  'IE520313', 2012),
             (  'IE521354', 2012),
             (  'IE521527', 2012)],
            names=['bv_id', 'year'], length=41934),
 2013: MultiIndex([('GB07114772', 2013),
             ('GB07114798', 2013),
             ('GB07114838', 2013),
             ('GB07114865', 2013),
             ('GB07114884', 2013),
             ('GB07114896', 2013),
             ('GB07114903', 2013),
             ('GB07114911', 2013),
             ('GB07114945', 2013),
             ('GB07114946', 2013),
             ...
             (  'IE536121', 2013),
             (  'IE536238', 2013),
             (  'IE536416', 2013),
             (  'IE536618', 2013),
             (  'IE536865', 2013),
             (  'IE536990', 2013),
             (  'IE537952', 2013),
             (  'IE538315', 2013),
             (  'IE539688', 2013),
             (  'IE547287', 2013)],
            names=['bv_id', 'year'], length=61180),
 2014: MultiIndex([('GB07114772', 2014),
             ('GB07114798', 2014),
             ('GB07114838', 2014),
             ('GB07114865', 2014),
             ('GB07114884', 2014),
             ('GB07114896', 2014),
             ('GB07114903', 2014),
             ('GB07114911', 2014),
             ('GB07114945', 2014),
             ('GB07114950', 2014),
             ...
             (  'IE551638', 2014),
             (  'IE551718', 2014),
             (  'IE551804', 2014),
             (  'IE551887', 2014),
             (  'IE551947', 2014),
             (  'IE553431', 2014),
             (  'IE554525', 2014),
             (  'IE554526', 2014),
             (  'IE554527', 2014),
             (  'IE557774', 2014)],
            names=['bv_id', 'year'], length=78947),
 2015: MultiIndex([('GB07114772', 2015),
             ('GB07114798', 2015),
             ('GB07114838', 2015),
             ('GB07114865', 2015),
             ('GB07114884', 2015),
             ('GB07114896', 2015),
             ('GB07114903', 2015),
             ('GB07114911', 2015),
             ('GB07114945', 2015),
             ('GB07114950', 2015),
             ...
             (  'IE569482', 2015),
             (  'IE570115', 2015),
             (  'IE570201', 2015),
             (  'IE570477', 2015),
             (  'IE570868', 2015),
             (  'IE571760', 2015),
             (  'IE573439', 2015),
             (  'IE573500', 2015),
             (  'IE573864', 2015),
             (  'IE574575', 2015)],
            names=['bv_id', 'year'], length=94155),
 2016: MultiIndex([('GB07114772', 2016),
             ('GB07114798', 2016),
             ('GB07114838', 2016),
             ('GB07114865', 2016),
             ('GB07114884', 2016),
             ('GB07114896', 2016),
             ('GB07114903', 2016),
             ('GB07114911', 2016),
             ('GB07114945', 2016),
             ('GB07114950', 2016),
             ...
             (  'IE591753', 2016),
             (  'IE591950', 2016),
             (  'IE592029', 2016),
             (  'IE592125', 2016),
             (  'IE592127', 2016),
             (  'IE593164', 2016),
             (  'IE593513', 2016),
             (  'IE597231', 2016),
             (  'IE600717', 2016),
             (  'IE601235', 2016)],
            names=['bv_id', 'year'], length=106714),
 2017: MultiIndex([('GB07114798', 2017),
             ('GB07114838', 2017),
             ('GB07114865', 2017),
             ('GB07114884', 2017),
             ('GB07114896', 2017),
             ('GB07114903', 2017),
             ('GB07114911', 2017),
             ('GB07114945', 2017),
             ('GB07114950', 2017),
             ('GB07114956', 2017),
             ...
             (  'IE600614', 2017),
             (  'IE600703', 2017),
             (  'IE600717', 2017),
             (  'IE601235', 2017),
             (  'IE601857', 2017),
             (  'IE602994', 2017),
             (  'IE605704', 2017),
             (  'IE609357', 2017),
             (  'IE610380', 2017),
             (  'IE610925', 2017)],
            names=['bv_id', 'year'], length=109943),
 2018: MultiIndex([('GB07114798', 2018),
             ('GB07114838', 2018),
             ('GB07114865', 2018),
             ('GB07114884', 2018),
             ('GB07114896', 2018),
             ('GB07114903', 2018),
             ('GB07114911', 2018),
             ('GB07114945', 2018),
             ('GB07114950', 2018),
             ('GB07114956', 2018),
             ...
             (  'IE600614', 2018),
             (  'IE600703', 2018),
             (  'IE600717', 2018),
             (  'IE601235', 2018),
             (  'IE601857', 2018),
             (  'IE602994', 2018),
             (  'IE605704', 2018),
             (  'IE609426', 2018),
             (  'IE610380', 2018),
             (  'IE610925', 2018)],
            names=['bv_id', 'year'], length=102528),
 2019: MultiIndex([('GB07114838', 2019),
             ('GB07114865', 2019),
             ('GB07114884', 2019),
             ('GB07114896', 2019),
             ('GB07114911', 2019),
             ('GB07114950', 2019),
             ('GB07114959', 2019),
             ('GB07114962', 2019),
             ('GB07114981', 2019),
             ('GB07114984', 2019),
             ...
             (  'IE598117', 2019),
             (  'IE599048', 2019),
             (  'IE600555', 2019),
             (  'IE600614', 2019),
             (  'IE600703', 2019),
             (  'IE605704', 2019),
             (  'IE609357', 2019),
             (  'IE609426', 2019),
             (  'IE610380', 2019),
             (  'IE610925', 2019)],
            names=['bv_id', 'year'], length=60559)}

In [13]:
_2011 = gby.groups[2011].droplevel('year')
print(_2011.shape)
_2015 = gby.groups[2015].droplevel('year')
print(_2015.shape)
_i = set(_2011).intersection(set(_2015))
len(_i)

(21308,)
(94155,)

18296

In [14]:
y_all = [2011,2012,2013,2014,2015,2016,2017,2018,2019]
all_9 = None
for y in y_all:
    current_year_bv_ids = set(gby.groups[y].droplevel('year'))
    if all_9 == None:
        all_9 = current_year_bv_ids
    else:
        all_9 = all_9.intersection(current_year_bv_ids)
len(all_9)

7073

In [15]:
import itertools
bvd_ids = all_9
tuples = list(itertools.product(bvd_ids,y_all))
select_index = pd.MultiIndex.from_tuples(tuples, names=['bv_id','year'])
select_index

MultiIndex([('GB07256264', 2011),
            ('GB07256264', 2012),
            ('GB07256264', 2013),
            ('GB07256264', 2014),
            ('GB07256264', 2015),
            ('GB07256264', 2016),
            ('GB07256264', 2017),
            ('GB07256264', 2018),
            ('GB07256264', 2019),
            ('GB07136022', 2011),
            ...
            ('GB07270337', 2019),
            ('GB07225684', 2011),
            ('GB07225684', 2012),
            ('GB07225684', 2013),
            ('GB07225684', 2014),
            ('GB07225684', 2015),
            ('GB07225684', 2016),
            ('GB07225684', 2017),
            ('GB07225684', 2018),
            ('GB07225684', 2019)],
           names=['bv_id', 'year'], length=63657)

In [16]:
all_nine_y = gifi.loc[select_index]
all_nine_y.sort_index(inplace=True)
all_nine_y.describe()

,total_assets_less_cur._liab._th_gbp,net_assets_th_gbp,net_tangible_assets_(liab.)_th_gbp,total_assets_th_gbp,net_current_assets_(working_capital)_th_gbp,shareholders_funds_th_gbp,current_assets_th_gbp,total_reserves_th_gbp,current_liabilities_th_gbp,solvency_ratio_(asset_based)_(%),...,impairment_th_gbp,dividends_th_gbp,preference_shares_th_gbp,management_of_liquid_resources_th_gbp,other_income_pre_gp_th_gbp,other_auditors_services_th_gbp,costs_of_reorganisation_th_gbp,non-audit_fees_paid_to_other_auditors_th_gbp,exceptional_items_pre_gp_th_gbp,profit_(loss)_on_sale_of_operations_th_gbp
count,63464.000000,63152.000000,63083.000000,62900.000000,62896.000000,61548.000000,61668.000000,57398.000000,55977.000000,53734.000000,...,23.000000,41.000000,22.000000,2.000000,5.000000,5.000000,2.000000,0.0,0.0,0.0
mean,565.610991,92.684250,537.057311,910.381958,76.383598,98.864126,424.390478,70.787833,-381.711939,30.043758,...,1621.458609,-31.866701,-532.857591,-3455.849500,-30.729000,0.882000,32.611500,NaN,NaN,NaN
std,8251.297532,4272.925248,8228.008782,10420.507271,4490.759962,4281.290531,6439.609836,4414.181445,5413.844560,43.972566,...,3340.613680,72.461875,850.947183,5012.185704,70.602452,1.316195,62.067712,NaN,NaN,NaN
min,-57951.776000,-114579.079352,-119059.000000,0.000862,-162089.000000,-104064.703000,0.000862,-104064.703000,-503436.373000,-100.000000,...,1.000000,-360.000000,-2714.489000,-7000.000000,-157.000000,0.100000,-11.277000,NaN,NaN,NaN
25%,0.008000,-0.356000,0.002000,5.595750,-3.150000,-0.513000,3.799500,-1.406000,-55.426000,0.958722,...,26.557000,-22.000000,-1347.312000,-5227.924750,0.001000,0.150000,10.667250,NaN,NaN,NaN
50%,3.090000,0.940000,2.751000,21.781000,0.529500,1.048000,16.054000,1.380000,-17.355000,21.907156,...,237.398000,-7.650000,-13.184500,-3455.849500,0.003000,0.350000,32.611500,NaN,NaN,NaN
75%,23.996000,11.603000,22.361000,81.417282,10.870500,12.322250,55.724750,13.306030,-5.370000,64.978981,...,1956.846000,-2.845464,-0.396250,-1683.774250,0.007000,0.600000,54.555750,NaN,NaN,NaN
max,457399.000000,421712.000000,457262.000000,518202.338568,392010.000000,421712.000000,511953.588000,421712.000000,-0.001000,100.000000,...,15398.539000,-0.001000,-0.010000,88.301000,3.344000,3.210000,76.500000,NaN,NaN,NaN

In [19]:
all_nine_y.head(36)

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114838 2011                               -0.505             -0.505
           2012                               -2.561             -2.561
           2013                                7.658              7.658
           2014                               21.344             21.344
           2015                               61.440             19.280
           2016                               22.798             22.798
           2017                               39.533             39.533
           2018                               44.736             44.736
           2019                               39.009             39.009
GB07114865 2011                               13.830             -6.493
           2012                                9.066            -11.257
           2013                                9.066            -11.257
           2014                                9.066            -11.257
           2015                               36.972              8.915
           2016                              135.507            135.507
           2017                              112.487            112.487
           2018                              120.646            120.646
           2019                               73.569             54.569
GB07114884 2011                                0.002              0.002
           2012                                0.002              0.002
           2013                               -2.995             -2.995
           2014                               -7.265             -7.265
           2015                               64.588              1.101
           2016                               60.029            -13.479
           2017                               27.708            -37.746
           2018                               35.040            -23.566
           2019                               46.494             -5.692
GB07114896 2011                               16.029             -3.136
           2012                               12.939             -2.147
           2013                               -5.465             -9.465
           2014                               -0.361             -3.461
           2015                                7.767             -2.035
           2016                                7.864             -3.578
           2017                                9.764              3.785
           2018                                0.193             -1.952
           2019                                0.193             -1.952

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114838 2011                              -0.505               32.892
           2012                              -2.561               33.273
           2013                               7.658               59.282
           2014                              21.344               66.893
           2015                              61.440               61.440
           2016                              22.798               69.024
           2017                              39.533               53.914
           2018                              44.736               78.849
           2019                              39.009               77.946
GB07114865 2011                              13.830               16.028
           2012                               5.052               10.592
           2013                               5.052               10.592
           2014                               5.052               10.592
           2015                              32.958               36.972
           2016                             135.507              172.596
           2017                             112.487              153.075
           2018                             120.646              160.939
           2019                              73.569              321.872
GB07114884 2011                               0.002                0.002
           2012                               0.002                0.002
           2013                              -2.995               13.902
           2014                              -7.265               35.675
           2015                              64.588               97.494
           2016                              60.029               78.379
           2017                              25.550               39.391
           2018                              33.451               46.890
           2019                              46.494               56.592
GB07114896 2011                              11.029               16.029
           2012                               9.983               23.820
           2013                              -8.421               19.118
           2014                              -3.361               14.276
           2015                               7.767               11.612
           2016                               4.864               10.578
           2017                               6.764                9.764
           2018                               0.193                0.193
           2019                               0.193                0.193

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114838 2011                                       -0.505
           2012                                       -2.561
           2013                                        7.658
           2014                                       16.693
           2015                                       57.417
           2016                                       18.540
           2017                                       34.853
           2018                                       14.023
           2019                                        8.670
GB07114865 2011                                        5.803
           2012                                        5.052
           2013                                        5.052
           2014                                        5.052
           2015                                        5.580
           2016                                      -11.038
           2017                                       31.007
           2018                                      113.731
           2019                                       58.846
GB07114884 2011                                        0.002
           2012                                        0.002
           2013                                       -8.541
           2014                                      -11.988
           2015                                       59.928
           2016                                       39.785
           2017                                       10.420
           2018                                       20.874
           2019                                       34.804
GB07114896 2011                                       11.029
           2012                                        7.951
           2013                                      -11.209
           2014                                       -4.700
           2015                                        3.445
           2016                                        3.631
           2017                                        5.537
           2018                                        0.193
           2019                                        0.193

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114838 2011                     -0.505                 32.892
           2012                     -2.561                 33.273
           2013                      7.658                 59.282
           2014                     21.344                 62.242
           2015                     19.280                 57.417
           2016                     22.798                 64.766
           2017                     39.533                 49.234
           2018                     44.736                 48.136
           2019                     39.009                 47.607
GB07114865 2011                     -6.493                  8.001
           2012                    -11.257                  6.578
           2013                    -11.257                  6.578
           2014                    -11.257                  6.578
           2015                      8.915                  5.580
           2016                    135.507                 26.051
           2017                    112.487                 71.595
           2018                    120.646                154.024
           2019                     54.569                307.149
GB07114884 2011                      0.002                  0.002
           2012                      0.002                  0.002
           2013                     -2.995                  8.356
           2014                     -7.265                 30.952
           2015                      1.101                 92.834
           2016                    -13.479                 58.135
           2017                    -37.746                 22.103
           2018                    -23.566                 32.724
           2019                     -5.692                 44.902
GB07114896 2011                     -3.136                 11.029
           2012                     -2.147                 18.832
           2013                     -9.465                 13.374
           2014                     -3.461                  9.937
           2015                     -2.035                  7.290
           2016                     -3.578                  6.345
           2017                      3.785                  5.537
           2018                     -1.952                  0.193
           2019                     -1.952                  0.193

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114838 2011                 -0.506                     -33.397
           2012                 -2.562                     -35.834
           2013                  7.657                     -51.624
           2014                 21.343                     -45.549
           2015                 19.279                         NaN
           2016                 22.797                     -46.226
           2017                 39.533                     -14.381
           2018                 44.736                     -34.113
           2019                 39.009                     -38.937
GB07114865 2011                 -6.593                      -2.198
           2012                -11.357                      -1.526
           2013                -11.357                      -1.526
           2014                -11.357                      -1.526
           2015                  8.815                         NaN
           2016                135.407                     -37.089
           2017                112.387                     -40.588
           2018                120.546                     -40.293
           2019                 54.569                    -248.303
GB07114884 2011                    NaN                         NaN
           2012                    NaN                         NaN
           2013                 -2.997                     -16.897
           2014                 -7.267                     -42.940
           2015                  1.101                     -32.906
           2016                -13.479                     -18.350
           2017                -37.748                     -11.683
           2018                -23.566                     -11.850
           2019                 -5.692                     -10.098
GB07114896 2011                 -3.136                         NaN
           2012                 -2.147                     -10.881
           2013                 -9.465                     -24.583
           2014                 -3.561                     -14.637
           2015                 -2.035                      -3.845
           2016                 -3.678                      -2.714
           2017                  3.685                         NaN
           2018                 -2.052                         NaN
           2019                 -2.052                         NaN

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114838 2011                         -1.535328  ...                NaN
           2012                         -7.696931  ...                NaN
           2013                         12.917918  ...                NaN
           2014                         31.907673  ...                NaN
           2015                         31.380208  ...                NaN
           2016                         33.029091  ...                NaN
           2017                         73.326038  ...                NaN
           2018                         56.736293  ...                NaN
           2019                         50.046186  ...                NaN
GB07114865 2011                        -40.510357  ...                NaN
           2012                               NaN  ...                NaN
           2013                               NaN  ...                NaN
           2014                               NaN  ...                NaN
           2015                         24.112842  ...                NaN
           2016                         78.511089  ...                NaN
           2017                         73.484893  ...                NaN
           2018                         74.963806  ...                NaN
           2019                         16.953634  ...                NaN
GB07114884 2011                        100.000000  ...                NaN
           2012                        100.000000  ...                NaN
           2013                        -21.543663  ...                NaN
           2014                        -20.364401  ...                NaN
           2015                          1.129300  ...                NaN
           2016                        -17.197208  ...                NaN
           2017                        -95.823919  ...                NaN
           2018                        -50.258051  ...                NaN
           2019                        -10.057959  ...                NaN
GB07114896 2011                        -19.564539  ...                NaN
           2012                         -9.013434  ...                NaN
           2013                        -49.508317  ...                NaN
           2014                        -24.243486  ...                NaN
           2015                        -17.524974  ...                NaN
           2016                        -33.824920  ...                NaN
           2017                         38.764850  ...                NaN
           2018                               NaN  ...                NaN
           2019                               NaN  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114838 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN
GB07114865 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN
GB07114884 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN
GB07114896 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114838 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN
GB07114865 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN
GB07114884 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN
GB07114896 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114838 2011                         NaN                             NaN
           2012                         NaN                             NaN

In [20]:
#all_nine_y.to_csv('all_nine_years.csv')
data['all_nine_years'] = all_nine_y
data.close()

In [21]:
all_nine_y

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114838 2011                            -0.505000          -0.505000
           2012                            -2.561000          -2.561000
           2013                             7.658000           7.658000
           2014                            21.344000          21.344000
           2015                            61.440000          19.280000
...                                              ...                ...
IE499325   2015                            35.464022         -10.169269
           2016                            29.900929          -1.520722
           2017                           -10.440070         -10.440070
           2018                            -4.032232          -4.032232
           2019                             7.051970           7.051970

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114838 2011                           -0.505000            32.892000
           2012                           -2.561000            33.273000
           2013                            7.658000            59.282000
           2014                           21.344000            66.893000
           2015                           61.440000            61.440000
...                                             ...                  ...
IE499325   2015                           35.464022            36.903620
           2016                           29.900929            31.698633
           2017                          -10.440070            38.558776
           2018                           -4.032232            44.091175
           2019                            7.051970            62.187813

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114838 2011                                    -0.505000
           2012                                    -2.561000
           2013                                     7.658000
           2014                                    16.693000
           2015                                    57.417000
...                                                      ...
IE499325   2015                                     6.109475
           2016                                     4.667466
           2017                                   -30.591285
           2018                                   -20.308646
           2019                                    -7.023606

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114838 2011                  -0.505000              32.892000
           2012                  -2.561000              33.273000
           2013                   7.658000              59.282000
           2014                  21.344000              62.242000
           2015                  19.280000              57.417000
...                                    ...                    ...
IE499325   2015                 -10.169269               7.549073
           2016                  -1.520722               6.465169
           2017                 -10.440070              18.407561
           2018                  -4.032232              27.814760
           2019                   7.051970              48.112236

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114838 2011              -0.506000                  -33.397000
           2012              -2.562000                  -35.834000
           2013               7.657000                  -51.624000
           2014              21.343000                  -45.549000
           2015              19.279000                         NaN
...                                ...                         ...
IE499325   2015             -10.241213                   -1.439597
           2016              -1.597026                   -1.797703
           2017             -10.527471                  -48.998846
           2018              -4.120022                  -48.123407
           2019               6.963333                  -55.135843

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114838 2011                         -1.535328  ...                NaN
           2012                         -7.696931  ...                NaN
           2013                         12.917918  ...                NaN
           2014                         31.907673  ...                NaN
           2015                         31.380208  ...                NaN
...                                           ...  ...                ...
IE499325   2015                        -27.556008  ...                NaN
           2016                         -4.797383  ...                NaN
           2017                        -27.075573  ...                NaN
           2018                         -9.145249  ...                NaN
           2019                         11.339761  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114838 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN
...                           ...                       ...
IE499325   2015               NaN                       NaN
           2016               NaN                       NaN
           2017               NaN                       NaN
           2018               NaN                       NaN
           2019               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114838 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN
...                                                ...
IE499325   2015                                    NaN
           2016                                    NaN
           2017                                    NaN
           2018                                    NaN
           2019                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114838 2011                         NaN                             NaN
           2012                         NaN                             NaN
           2013                         NaN                             NaN
           2014                         NaN                             NaN
           2015                         NaN                             NaN
...                                     ...                             ...
IE499325   2015                         NaN                             NaN
           2016                         NaN                             NaN
           2017                         NaN                             NaN
           2018                         NaN                             NaN
           2019                         NaN                             NaN

                 costs_of_reorganisation_th_gbp  \
bv_id      year
GB07114838 2011                             NaN
           2012                             NaN
           2013                             NaN
           2014                             NaN
           2015                             NaN
...                                         ...
IE499325   2015                             NaN
           2016                             NaN
           2017                             NaN
           2018                             NaN
           2019                             NaN

                 non-audit_fees_paid_to_other_auditors_th_gbp  \
bv_id      year
GB07114838 2011                                           NaN
           2012                                           NaN
           2013                                           NaN
           2014                                           NaN
           2015                                           NaN
...                                                       ...
IE499325   2015                                           NaN
           2016                                           NaN
           2017                                           NaN
           2018                                           NaN
           2019                                           NaN

                 exceptional_items_pre_gp_th_gbp  \
bv_id      year
GB07114838 2011                              NaN
           2012                              NaN
           2013                              NaN
           2014                              NaN
           2015                              NaN
...                                          ...
IE499325   2015                              NaN
           2016                              NaN
           2017                              NaN
           2018                              NaN
           2019                              NaN

                 profit_(loss)_on_sale_of_operations_th_gbp
bv_id      year
GB07114838 2011                                         NaN
           2012                                         NaN
           2013                                         NaN
           2014                                         NaN
           2015                                         NaN
...                                                     ...
IE499325   2015                                         NaN
           2016                                         NaN
           2017                                         NaN
           2018                                         NaN
           2019                                         NaN

[63657 rows x 177 columns]