In [1]:
import pandas as pd

In [2]:
gifi = pd.HDFStore('bdv-gifi-all.h5')
size_tuples = []
for gifi_column_key in gifi.keys():
    column_df = gifi.get(gifi_column_key)
    size_tuples.append((gifi_column_key, column_df.size))
    

top_columns = sorted(size_tuples, key=lambda col_values: -1 * col_values[1])
top_columns

[('/total_assets_less_cur._liab._th_gbp', 675367),
 ('/net_assets_th_gbp', 672467),
 ('/net_tangible_assets_(liab.)_th_gbp', 671298),
 ('/total_assets_th_gbp', 666901),
 ('/net_current_assets_(working_capital)_th_gbp', 662191),
 ('/shareholders_funds_th_gbp', 657085),
 ('/current_assets_th_gbp', 646126),
 ('/total_reserves_th_gbp', 605651),
 ('/current_liabilities_th_gbp', 569495),
 ('/solvency_ratio_(asset_based)_(%)', 561279),
 ('/current_ratio_(x)', 548680),
 ('/liquidity_ratio_(x)', 547445),
 ('/total_other_current_liabilities_th_gbp', 543473),
 ('/other_current_assets_th_gbp', 457799),
 ('/bank_&_deposits_th_gbp', 455054),
 ('/other_current_liabilities_th_gbp', 448984),
 ('/profit_(loss)_account_th_gbp', 441665),
 ('/issued_capital_th_gbp', 425106),
 ('/ordinary_shares_th_gbp', 424124),
 ('/other_debtors_th_gbp', 409895),
 ('/fixed_assets_th_gbp', 379093),
 ('/turnover_th_gbp', 353901),
 ('/tangible_assets_th_gbp', 328038),
 ('/ebitda_th_gbp', 293455),
 ('/operating_profit_th_gbp', 293455),
 ('/profit_(loss)_before_interest_paid_th_gbp', 290993),
 ('/profit_(loss)_after_tax_th_gbp', 289257),
 ('/profit_(loss)_before_tax_th_gbp', 288729),
 ('/profit_(loss)_before_taxation_th_gbp', 288729),
 ('/profit_(loss)_for_period_[=net_income]_th_gbp', 288448),
 ('/retained_profit(loss)_th_gbp', 286047),
 ('/administration_expenses_th_gbp', 282675),
 ('/return_on_total_assets_(%)', 269705),
 ('/solvency_ratio_(liability_based)_(%)', 256523),
 ('/ebit_margin_(%)', 250673),
 ('/return_on_capital_employed', 245745),
 ('/return_on_capital_employed_(%)', 245745),
 ('/profit_margin', 243549),
 ('/profit_margin_(%)', 243549),
 ('/other_fixed_assets_th_gbp', 236406),
 ('/working_capital_needs_th_gbp', 229244),
 ('/depreciation_th_gbp', 228899),
 ('/number_of_employees', 220246),
 ('/long_term_liabilities_th_gbp', 201684),
 ('/net_assets_turnover_(x)', 199307),
 ('/shareholders_liquidity_ratio_(x)', 178717),
 ('/other_reserves_th_gbp', 177540),
 ('/gross_profit_th_gbp', 153927),
 ('/fixed_assets_turnover_(x)', 150954),
 ('/gross_margin_(%)', 146791),
 ('/berry_ratio_(x)', 146210),
 ('/return_on_shareholders_funds', 140107),
 ('/return_on_shareholders_funds_(%)', 140107),
 ('/short_term_loans_&_overdrafts_th_gbp', 137364),
 ('/trade_creditors_th_gbp', 136593),
 ('/taxation_th_gbp', 134599),
 ('/trade_debtors_th_gbp', 127290),
 ('/cost_of_sales_th_gbp', 126425),
 ('/social_securities_&_v.a.t._th_gbp', 118521),
 ('/accruals_&_def._inc._(short_t.)_th_gbp', 117906),
 ('/ebitda_margin_(%)', 114691),
 ('/total_other_long_term_liab._th_gbp', 113368),
 ('/gearing_(%)', 107874),
 ('/stock_&_w.i.p._th_gbp', 95191),
 ('/creditors_payment_(days)', 93390),
 ('/other_long_term_liab._th_gbp', 90259),
 ('/debtor_collection_(days)', 89001),
 ('/debtors_turnover_(x)', 88083),
 ('/remuneration_th_gbp', 86777),
 ('/wages_&_salaries_th_gbp', 86191),
 ('/depreciation_other_assets_th_gbp', 85153),
 ('/stock_th_gbp', 81796),
 ('/shareholders_funds_per_employee_(unit)_gbp', 79611),
 ('/corporation_tax_th_gbp', 77585),
 ('/salaries/turnover', 77086),
 ('/turnover_per_employee_(unit)_gbp', 76716),
 ('/working_capital_per_employee_(unit)_gbp', 76584),
 ('/profit_per_employee_(unit)_gbp', 76349),
 ('/net_interest_th_gbp', 74929),
 ('/plant_&_vehicles_th_gbp', 73400),
 ('/prepayments_th_gbp', 73127),
 ('/other_operating_income/costs_pre_op_th_gbp', 68944),
 ('/long_term_debt_th_gbp', 65076),
 ('/investments_th_gbp', 64890),
 ("/directors'_remuneration_th_gbp", 64609),
 ('/asset_cover_(x)', 64355),
 ("/directors'_fees_th_gbp", 63415),
 ('/group_loans_(short_t.)_th_gbp', 62324),
 ('/plant_th_gbp', 59433),
 ('/interest_paid_th_gbp', 58081),
 ('/non-audit_fee_th_gbp', 57683),
 ('/total_other_income_&_int._received_th_gbp', 54689),
 ('/audit_fee_th_gbp', 52069),
 ('/interest_cover_(x)', 51333),
 ('/non-tax_advisory_services_th_gbp', 49257),
 ('/other_interest_paid_th_gbp', 48934),
 ('/provisions_for_other_liab._th_gbp', 48283),
 ('/average_remuneration_per_employee_(unit)_gbp', 45814),
 ('/group_loans_(asset)_th_gbp', 45075),
 ('/national_turnover_th_gbp', 44850),
 ('/interest_received_th_gbp', 42484),
 ('/intangible_assets_th_gbp', 40552),
 ('/stock_turnover_(x)', 40432),
 ('/director_loans_(short_t.)_th_gbp', 38104),
 ('/fixtures_&_fittings_th_gbp', 37071),
 ('/depreciation_owned_assets_th_gbp', 36734),
 ('/bank_overdrafts_th_gbp', 34943),
 ('/other_provisions_th_gbp', 32654),
 ('/cash_in(out)flow_operat._activ._th_gbp', 31291),
 ('/social_security_costs_th_gbp', 30841),
 ('/increase(decrease)_cash_&_equiv._th_gbp', 29540),
 ('/accruals_&_def._inc._(long_t.)_th_gbp', 29100),
 ('/deferred_taxation_th_gbp', 28736),
 ('/total_amortization_and_impairment_th_gbp', 28418),
 ('/other_long_term_loans_th_gbp', 27055),
 ('/land_&_buildings_th_gbp', 25539),
 ('/vehicles_th_gbp', 23494),
 ('/director_loans_(long_t.)_th_gbp', 23222),
 ('/other_income_th_gbp', 18657),
 ('/other_short_term_loans_th_gbp', 18313),
 ('/pension_costs_th_gbp', 18078),
 ('/cash_out(in)flow_from_financing_th_gbp', 18032),
 ('/freehold_land_th_gbp', 16950),
 ('/deferred_tax_th_gbp', 16634),
 ('/amortisation_th_gbp', 16488),
 ('/group_loans_(long_t.)_th_gbp', 16148),
 ('/total_operating_lease_rentals_th_gbp', 15600),
 ('/capital_expenditure_&_financ._invest._th_gbp', 13338),
 ('/foreign_exchange_gains/losses_th_gbp', 12762),
 ('/paid_to_bank_th_gbp', 11706),
 ('/share_premium_account_th_gbp', 11194),
 ('/cash_in(out)flow_ret._on_invest._th_gbp', 10999),
 ('/leasehold_land_th_gbp', 9479),
 ('/hire_purch._&_leas._(short_t.)_th_gbp', 9266),
 ('/other_staff_costs_th_gbp', 7907),
 ('/hire_purch._&_leas._(long_t.)_th_gbp', 7683),
 ('/overseas_turnover_th_gbp', 6804),
 ('/tax_advice_th_gbp', 6738),
 ('/directors_loans_(asset)_th_gbp', 6465),
 ('/finished_goods_th_gbp', 6032),
 ('/revaluation_reserves_th_gbp', 5680),
 ('/land_&_building_or_property_rents_&_other_th_gbp', 5201),
 ('/pension_contribution_th_gbp', 5097),
 ('/cash_out(in)flow_investing_activ._th_gbp', 5080),
 ('/w.i.p._th_gbp', 4973),
 ('/highest_paid_director_th_gbp', 4277),
 ('/hire_of_plant_&_machinery_th_gbp', 4186),
 ('/hire_purchase_(short_t.)_th_gbp', 3603),
 ('/hire_purchase_(long_t.)_th_gbp', 2799),
 ('/other_emoluments_th_gbp', 2364),
 ('/leasing_(short_t.)_th_gbp', 2350),
 ('/paid_on_hire_purchase_th_gbp', 2206),
 ('/pension_liabilities_th_gbp', 1944),
 ('/leasing_(long_t.)_th_gbp', 1862),
 ('/exceptional_items_th_gbp', 1589),
 ('/exceptional_items_pre_op_th_gbp', 1171),
 ('/equity_dividends_paid_th_gbp', 1135),
 ('/extraordinary_items_th_gbp', 897),
 ('/balance_sheet_minorities_th_gbp', 857),
 ('/other_exceptional_items_th_gbp', 837),
 ('/minority_interests_th_gbp', 822),
 ('/profit_(loss)_on_disposal_th_gbp', 778),
 ('/research_&_development_th_gbp', 748),
 ('/other_shares_th_gbp', 520),
 ('/acquisition_&_disposal_th_gbp', 422),
 ('/impairment_tangibles_th_gbp', 406),
 ('/paid_on_leasing_th_gbp', 400),
 ('/impairment_th_gbp', 398),
 ('/dividends_th_gbp', 394),
 ('/preference_shares_th_gbp', 385),
 ('/management_of_liquid_resources_th_gbp', 89),
 ('/other_income_pre_gp_th_gbp', 65),
 ('/other_auditors_services_th_gbp', 53),
 ('/costs_of_reorganisation_th_gbp', 28),
 ('/non-audit_fees_paid_to_other_auditors_th_gbp', 17),
 ('/exceptional_items_pre_gp_th_gbp', 7),
 ('/profit_(loss)_on_sale_of_operations_th_gbp', 0)]

In [7]:
solvency_ratio = gifi.get("solvency_ratio_(asset_based)_(%)")
solvency_ratio.head(25)

                 solvency_ratio_(asset_based)_(%)
bv_id      year
GB07114772 2011                          1.262708
           2012                        100.000000
           2013                        100.000000
           2014                        100.000000
           2015                        100.000000
           2016                        100.000000
GB07114798 2017                        100.000000
           2018                        100.000000
GB07114838 2011                         -1.535328
           2012                         -7.696931
           2013                         12.917918
           2014                         31.907673
           2015                         31.380208
           2016                         33.029091
           2017                         73.326038
           2018                         56.736293
           2019                         50.046186
GB07114865 2011                        -40.510357
           2015                         24.112842
           2016                         78.511089
           2017                         73.484893
           2018                         74.963806
           2019                         16.953634
GB07114872 2011                          2.288136
           2012                         19.280749

In [11]:
net_current_assets_working_capital_th_gbp = gifi.get("net_current_assets_(working_capital)_th_gbp")
net_current_assets_working_capital_th_gbp.head(25)

                 net_current_assets_(working_capital)_th_gbp
bv_id      year
GB07114772 2011                                        0.313
           2012                                        0.313
           2013                                        0.313
           2014                                        0.313
           2015                                        0.313
           2016                                        0.313
GB07114798 2011                                       -0.436
           2012                                       -1.253
           2013                                       -2.905
           2014                                       -2.761
           2015                                       -2.761
           2016                                       -2.761
           2017                                        0.100
           2018                                        0.100
GB07114838 2011                                       -0.505
           2012                                       -2.561
           2013                                        7.658
           2014                                       16.693
           2015                                       57.417
           2016                                       18.540
           2017                                       34.853
           2018                                       14.023
           2019                                        8.670
GB07114865 2011                                        5.803
           2012                                        5.052

In [6]:
ta = gifi.get("total_assets_less_cur._liab._th_gbp")
ta.head(25)

                 total_assets_less_cur._liab._th_gbp
bv_id      year
GB07114772 2011                                0.313
           2012                                0.313
           2013                                0.313
           2014                                0.313
           2015                                0.313
           2016                                0.313
GB07114798 2011                               -0.436
           2012                               -1.253
           2013                               -2.905
           2014                               -2.761
           2015                               -2.761
           2016                               -2.761
           2017                                0.100
           2018                                0.100
GB07114838 2011                               -0.505
           2012                               -2.561
           2013                                7.658
           2014                               21.344
           2015                               61.440
           2016                               22.798
           2017                               39.533
           2018                               44.736
           2019                               39.009
GB07114865 2011                               13.830
           2012                                9.066

In [8]:
column_df = None
joined_df = None
i=0
for (gifi_column_key, size) in top_columns:
    column_df = gifi.get(gifi_column_key)
    print(column_df.memory_usage(index=True))
    if joined_df is None:
        joined_df = column_df
    else:
        joined_df = joined_df.join(column_df,on=['bv_id','year'], how='outer')
        joined_df.info(memory_usage=True)
        #joined_df.memory_usage(index=True)
    i=i+1
    print(str(i))
    if i > 3:
        break
gifi_joined = pd.HDFStore('bdv-gifi-3.h5')
gifi_joined.put('gifi', joined_df)
gifi_joined.close()

Index                                  9623206
total_assets_less_cur._liab._th_gbp    5402936
dtype: int64
1
Index                9608882
net_assets_th_gbp    5379736
dtype: int64
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 682354 entries, ('GB07114772', 2011) to ('IE570635', 2016)
Data columns (total 2 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   total_assets_less_cur._liab._th_gbp  681201 non-null  float64
 1   net_assets_th_gbp                    678301 non-null  float64
dtypes: float64(2)
memory usage: 14.6+ MB
2
Index                                 9602813
net_tangible_assets_(liab.)_th_gbp    5370384
dtype: int64
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 694022 entries, ('GB07114772', 2011) to ('IE570635', 2016)
Data columns (total 3 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   total_assets_less_cur._liab._th_gbp  692869 non-null  float64
 1   net_assets_th_gbp                    689969 non-null  float64
 2   net_tangible_assets_(liab.)_th_gbp   688800 non-null  float64
dtypes: float64(3)
memory usage: 20.2+ MB
3
Index                  9579124
total_assets_th_gbp    5335208
dtype: int64
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 717016 entries, ('GB07114772', 2011) to ('IE570635', 2016)
Data columns (total 4 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   total_assets_less_cur._liab._th_gbp  715863 non-null  float64
 1   net_assets_th_gbp                    712953 non-null  float64
 2   net_tangible_assets_(liab.)_th_gbp   711784 non-null  float64
 3   total_assets_th_gbp                  707133 non-null  float64
dtypes: float64(4)
memory usage: 26.3+ MB
4

In [15]:
column_df = None
net_assets_th_gbp_turnover_th_gbp = None
i=0
for gifi_column_key in ['net_assets_th_gbp','turnover_th_gbp']:
    column_df = gifi.get(gifi_column_key)
    print(column_df.memory_usage(index=True))
    if net_assets_th_gbp_turnover_th_gbp is None:
        net_assets_th_gbp_turnover_th_gbp = column_df
    else:
        net_assets_th_gbp_turnover_th_gbp = net_assets_th_gbp_turnover_th_gbp.join(column_df,on=['bv_id','year'], how='inner')
        net_assets_th_gbp_turnover_th_gbp.info(memory_usage=True)
        #joined_df.memory_usage(index=True)
    i=i+1
    print(str(i))
    if i > 3:
        break

Index                9608882
net_assets_th_gbp    5379736
dtype: int64
1
Index              8016052
turnover_th_gbp    2831208
dtype: int64
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 680410 entries, ('GB07114772', 2011) to ('IE588665', 2016)
Data columns (total 2 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   net_assets_th_gbp  675301 non-null  float64
 1   turnover_th_gbp    356735 non-null  float64
dtypes: float64(2)
memory usage: 14.6+ MB
2

In [16]:
net_assets_th_gbp_turnover_th_gbp.head(32)

                 net_assets_th_gbp  turnover_th_gbp
bv_id      year
GB07114772 2011              0.313           68.163
           2012              0.313              NaN
           2013              0.313              NaN
           2014              0.313              NaN
           2015              0.313              NaN
           2016              0.313            0.065
GB07114798 2011             -0.436              NaN
           2012             -1.253              NaN
           2013             -2.905            0.550
           2014             -2.761            0.915
           2015             -2.761              NaN
           2016             -2.761              NaN
           2017              0.100              NaN
           2018              0.100            0.006
GB07114838 2011             -0.505              NaN
           2012             -2.561              NaN
           2013              7.658              NaN
           2014             21.344          356.282
           2015             19.280              NaN
           2016             22.798              NaN
           2017             39.533              NaN
           2018             44.736              NaN
           2019             39.009         1335.702
GB07114865 2011             -6.493              NaN
           2012            -11.257              NaN
           2013            -11.257              NaN
           2014            -11.257              NaN
           2015              8.915              NaN
           2016            135.507              NaN
           2017            112.487              NaN
           2018            120.646          193.552
           2019             54.569         1018.344

In [ ]:
net_assets_th_gbp_turnover_th_gbp.

In [15]:
t_a_l_c_l = gifi.get('total_assets_less_cur._liab._th_gbp')
t_a_l_c_l.loc['GB07114772']

      total_assets_less_cur._liab._th_gbp
year
2011                                0.313
2012                                0.313
2013                                0.313
2014                                0.313
2015                                0.313
2016                                0.313