In [1]:
import pandas as pd
import numpy as np
import re

In [3]:
gifi = pd.HDFStore('bdv-gifi-all.h5')
size_tuples = []
for gifi_column_key in gifi.keys():
    column_df = gifi.get(gifi_column_key)
    size_tuples.append((gifi_column_key, column_df.size))
    

top_columns = sorted(size_tuples, key=lambda col_values: -1 * col_values[1])
top_columns

[('/total_assets_less_cur._liab._th_gbp', 675367),
 ('/net_assets_th_gbp', 672467),
 ('/net_tangible_assets_(liab.)_th_gbp', 671298),
 ('/total_assets_th_gbp', 666901),
 ('/net_current_assets_(working_capital)_th_gbp', 662191),
 ('/shareholders_funds_th_gbp', 657085),
 ('/current_assets_th_gbp', 646126),
 ('/total_reserves_th_gbp', 605651),
 ('/current_liabilities_th_gbp', 569495),
 ('/solvency_ratio_(asset_based)_(%)', 561279),
 ('/current_ratio_(x)', 548680),
 ('/liquidity_ratio_(x)', 547445),
 ('/total_other_current_liabilities_th_gbp', 543473),
 ('/other_current_assets_th_gbp', 457799),
 ('/bank_&_deposits_th_gbp', 455054),
 ('/other_current_liabilities_th_gbp', 448984),
 ('/profit_(loss)_account_th_gbp', 441665),
 ('/issued_capital_th_gbp', 425106),
 ('/ordinary_shares_th_gbp', 424124),
 ('/other_debtors_th_gbp', 409895),
 ('/fixed_assets_th_gbp', 379093),
 ('/turnover_th_gbp', 353901),
 ('/tangible_assets_th_gbp', 328038),
 ('/ebitda_th_gbp', 293455),
 ('/operating_profit_th_gbp', 293455),
 ('/profit_(loss)_before_interest_paid_th_gbp', 290993),
 ('/profit_(loss)_after_tax_th_gbp', 289257),
 ('/profit_(loss)_before_tax_th_gbp', 288729),
 ('/profit_(loss)_before_taxation_th_gbp', 288729),
 ('/profit_(loss)_for_period_[=net_income]_th_gbp', 288448),
 ('/retained_profit(loss)_th_gbp', 286047),
 ('/administration_expenses_th_gbp', 282675),
 ('/return_on_total_assets_(%)', 269705),
 ('/solvency_ratio_(liability_based)_(%)', 256523),
 ('/ebit_margin_(%)', 250673),
 ('/return_on_capital_employed', 245745),
 ('/return_on_capital_employed_(%)', 245745),
 ('/profit_margin', 243549),
 ('/profit_margin_(%)', 243549),
 ('/other_fixed_assets_th_gbp', 236406),
 ('/working_capital_needs_th_gbp', 229244),
 ('/depreciation_th_gbp', 228899),
 ('/number_of_employees', 220246),
 ('/long_term_liabilities_th_gbp', 201684),
 ('/net_assets_turnover_(x)', 199307),
 ('/shareholders_liquidity_ratio_(x)', 178717),
 ('/other_reserves_th_gbp', 177540),
 ('/gross_profit_th_gbp', 153927),
 ('/fixed_assets_turnover_(x)', 150954),
 ('/gross_margin_(%)', 146791),
 ('/berry_ratio_(x)', 146210),
 ('/return_on_shareholders_funds', 140107),
 ('/return_on_shareholders_funds_(%)', 140107),
 ('/short_term_loans_&_overdrafts_th_gbp', 137364),
 ('/trade_creditors_th_gbp', 136593),
 ('/taxation_th_gbp', 134599),
 ('/trade_debtors_th_gbp', 127290),
 ('/cost_of_sales_th_gbp', 126425),
 ('/social_securities_&_v.a.t._th_gbp', 118521),
 ('/accruals_&_def._inc._(short_t.)_th_gbp', 117906),
 ('/ebitda_margin_(%)', 114691),
 ('/total_other_long_term_liab._th_gbp', 113368),
 ('/gearing_(%)', 107874),
 ('/stock_&_w.i.p._th_gbp', 95191),
 ('/creditors_payment_(days)', 93390),
 ('/other_long_term_liab._th_gbp', 90259),
 ('/debtor_collection_(days)', 89001),
 ('/debtors_turnover_(x)', 88083),
 ('/remuneration_th_gbp', 86777),
 ('/wages_&_salaries_th_gbp', 86191),
 ('/depreciation_other_assets_th_gbp', 85153),
 ('/stock_th_gbp', 81796),
 ('/shareholders_funds_per_employee_(unit)_gbp', 79611),
 ('/corporation_tax_th_gbp', 77585),
 ('/salaries/turnover', 77086),
 ('/turnover_per_employee_(unit)_gbp', 76716),
 ('/working_capital_per_employee_(unit)_gbp', 76584),
 ('/profit_per_employee_(unit)_gbp', 76349),
 ('/net_interest_th_gbp', 74929),
 ('/plant_&_vehicles_th_gbp', 73400),
 ('/prepayments_th_gbp', 73127),
 ('/other_operating_income/costs_pre_op_th_gbp', 68944),
 ('/long_term_debt_th_gbp', 65076),
 ('/investments_th_gbp', 64890),
 ("/directors'_remuneration_th_gbp", 64609),
 ('/asset_cover_(x)', 64355),
 ("/directors'_fees_th_gbp", 63415),
 ('/group_loans_(short_t.)_th_gbp', 62324),
 ('/plant_th_gbp', 59433),
 ('/interest_paid_th_gbp', 58081),
 ('/non-audit_fee_th_gbp', 57683),
 ('/total_other_income_&_int._received_th_gbp', 54689),
 ('/audit_fee_th_gbp', 52069),
 ('/interest_cover_(x)', 51333),
 ('/non-tax_advisory_services_th_gbp', 49257),
 ('/other_interest_paid_th_gbp', 48934),
 ('/provisions_for_other_liab._th_gbp', 48283),
 ('/average_remuneration_per_employee_(unit)_gbp', 45814),
 ('/group_loans_(asset)_th_gbp', 45075),
 ('/national_turnover_th_gbp', 44850),
 ('/interest_received_th_gbp', 42484),
 ('/intangible_assets_th_gbp', 40552),
 ('/stock_turnover_(x)', 40432),
 ('/director_loans_(short_t.)_th_gbp', 38104),
 ('/fixtures_&_fittings_th_gbp', 37071),
 ('/depreciation_owned_assets_th_gbp', 36734),
 ('/bank_overdrafts_th_gbp', 34943),
 ('/other_provisions_th_gbp', 32654),
 ('/cash_in(out)flow_operat._activ._th_gbp', 31291),
 ('/social_security_costs_th_gbp', 30841),
 ('/increase(decrease)_cash_&_equiv._th_gbp', 29540),
 ('/accruals_&_def._inc._(long_t.)_th_gbp', 29100),
 ('/deferred_taxation_th_gbp', 28736),
 ('/total_amortization_and_impairment_th_gbp', 28418),
 ('/other_long_term_loans_th_gbp', 27055),
 ('/land_&_buildings_th_gbp', 25539),
 ('/vehicles_th_gbp', 23494),
 ('/director_loans_(long_t.)_th_gbp', 23222),
 ('/other_income_th_gbp', 18657),
 ('/other_short_term_loans_th_gbp', 18313),
 ('/pension_costs_th_gbp', 18078),
 ('/cash_out(in)flow_from_financing_th_gbp', 18032),
 ('/freehold_land_th_gbp', 16950),
 ('/deferred_tax_th_gbp', 16634),
 ('/amortisation_th_gbp', 16488),
 ('/group_loans_(long_t.)_th_gbp', 16148),
 ('/total_operating_lease_rentals_th_gbp', 15600),
 ('/capital_expenditure_&_financ._invest._th_gbp', 13338),
 ('/foreign_exchange_gains/losses_th_gbp', 12762),
 ('/paid_to_bank_th_gbp', 11706),
 ('/share_premium_account_th_gbp', 11194),
 ('/cash_in(out)flow_ret._on_invest._th_gbp', 10999),
 ('/leasehold_land_th_gbp', 9479),
 ('/hire_purch._&_leas._(short_t.)_th_gbp', 9266),
 ('/other_staff_costs_th_gbp', 7907),
 ('/hire_purch._&_leas._(long_t.)_th_gbp', 7683),
 ('/overseas_turnover_th_gbp', 6804),
 ('/tax_advice_th_gbp', 6738),
 ('/directors_loans_(asset)_th_gbp', 6465),
 ('/finished_goods_th_gbp', 6032),
 ('/revaluation_reserves_th_gbp', 5680),
 ('/land_&_building_or_property_rents_&_other_th_gbp', 5201),
 ('/pension_contribution_th_gbp', 5097),
 ('/cash_out(in)flow_investing_activ._th_gbp', 5080),
 ('/w.i.p._th_gbp', 4973),
 ('/highest_paid_director_th_gbp', 4277),
 ('/hire_of_plant_&_machinery_th_gbp', 4186),
 ('/hire_purchase_(short_t.)_th_gbp', 3603),
 ('/hire_purchase_(long_t.)_th_gbp', 2799),
 ('/other_emoluments_th_gbp', 2364),
 ('/leasing_(short_t.)_th_gbp', 2350),
 ('/paid_on_hire_purchase_th_gbp', 2206),
 ('/pension_liabilities_th_gbp', 1944),
 ('/leasing_(long_t.)_th_gbp', 1862),
 ('/exceptional_items_th_gbp', 1589),
 ('/exceptional_items_pre_op_th_gbp', 1171),
 ('/equity_dividends_paid_th_gbp', 1135),
 ('/extraordinary_items_th_gbp', 897),
 ('/balance_sheet_minorities_th_gbp', 857),
 ('/other_exceptional_items_th_gbp', 837),
 ('/minority_interests_th_gbp', 822),
 ('/profit_(loss)_on_disposal_th_gbp', 778),
 ('/research_&_development_th_gbp', 748),
 ('/other_shares_th_gbp', 520),
 ('/acquisition_&_disposal_th_gbp', 422),
 ('/impairment_tangibles_th_gbp', 406),
 ('/paid_on_leasing_th_gbp', 400),
 ('/impairment_th_gbp', 398),
 ('/dividends_th_gbp', 394),
 ('/preference_shares_th_gbp', 385),
 ('/management_of_liquid_resources_th_gbp', 89),
 ('/other_income_pre_gp_th_gbp', 65),
 ('/other_auditors_services_th_gbp', 53),
 ('/costs_of_reorganisation_th_gbp', 28),
 ('/non-audit_fees_paid_to_other_auditors_th_gbp', 17),
 ('/exceptional_items_pre_gp_th_gbp', 7),
 ('/profit_(loss)_on_sale_of_operations_th_gbp', 0)]

In [4]:
talcl  = gifi.get('total_assets_less_cur._liab._th_gbp')
talcl.reset_index(inplace=True)
print(talcl.shape)
talcl.drop_duplicates(subset=['bv_id','year'], inplace=True)
print(talcl.shape)
df1 =talcl

(675367, 3)
(672445, 3)

In [56]:
net_assets_th_gbp  = gifi.get('net_assets_th_gbp')
net_assets_th_gbp.reset_index(inplace=True)# to_csv('net_assets_th_gbp.csv')
print(net_assets_th_gbp.shape)
net_assets_th_gbp.drop_duplicates(subset=['bv_id','year'], inplace=True)
print(net_assets_th_gbp.shape)
#net_assets_th_gbp

(672467, 3)
(669538, 3)

In [57]:
two = pd.merge(talcl,net_assets_th_gbp, on=['bv_id','year'], how='outer',sort=True)
#two.to_csv('two.csv')
print(two.shape)
two.drop_duplicates(subset=['bv_id','year'], inplace=True)
print(two.shape)

(673586, 4)
(673586, 4)

In [58]:
data = pd.HDFStore('bdv-data.h5')
print(data.keys())

['/flat', '/gifi']

In [59]:
column_df = None
joined_df = None
i=0
for (gifi_column_key, size) in top_columns:
    column_df = gifi.get(gifi_column_key).reset_index()
    column_df.drop_duplicates(subset=['bv_id','year'], inplace=True,ignore_index=True)
    print("Column shape going into merge " + str(column_df.shape))
    if joined_df is None:
        joined_df = column_df
    else:
        print("Joined shape going onto merge " + str(joined_df.shape))
        joined_df = pd.merge(joined_df,column_df,on=['bv_id','year'], how='outer')
        print("Joined shape after merge " + str(joined_df.shape))
        joined_df.drop_duplicates(subset=['bv_id','year'], inplace=True,ignore_index=True)
    joined_df.info(memory_usage=True)
    i=i+1
    print(str(i))

joined_df.set_index(['bv_id','year'],inplace=True)
data['gifi'] = joined_df
data.close()
joined_df.to_csv('gifi.csv')

Column shape going into merge (672445, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672445 entries, 0 to 672444
Data columns (total 3 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   bv_id                                672445 non-null  object
 1   year                                 672445 non-null  int64
 2   total_assets_less_cur._liab._th_gbp  672445 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 15.4+ MB
1
Column shape going into merge (669538, 3)
Joined shape going onto merge (672445, 3)
Joined shape after merge (673586, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673586 entries, 0 to 673585
Data columns (total 4 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   bv_id                                673586 non-null  object
 1   year                                 673586 non-null  int64
 2   total_assets_less_cur._liab._th_gbp  672445 non-null  float64
 3   net_assets_th_gbp                    669538 non-null  float64
dtypes: float64(2), int64(1), object(1)
memory usage: 20.6+ MB
2
Column shape going into merge (668381, 3)
Joined shape going onto merge (673586, 4)
Joined shape after merge (673586, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673586 entries, 0 to 673585
Data columns (total 5 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   bv_id                                673586 non-null  object
 1   year                                 673586 non-null  int64
 2   total_assets_less_cur._liab._th_gbp  672445 non-null  float64
 3   net_assets_th_gbp                    669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp   668381 non-null  float64
dtypes: float64(3), int64(1), object(1)
memory usage: 25.7+ MB
3
Column shape going into merge (664023, 3)
Joined shape going onto merge (673586, 5)
Joined shape after merge (673586, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673586 entries, 0 to 673585
Data columns (total 6 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   bv_id                                673586 non-null  object
 1   year                                 673586 non-null  int64
 2   total_assets_less_cur._liab._th_gbp  672445 non-null  float64
 3   net_assets_th_gbp                    669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp   668381 non-null  float64
 5   total_assets_th_gbp                  664023 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 30.8+ MB
4
Column shape going into merge (659341, 3)
Joined shape going onto merge (673586, 6)
Joined shape after merge (673586, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673586 entries, 0 to 673585
Data columns (total 7 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        673586 non-null  object
 1   year                                         673586 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
dtypes: float64(5), int64(1), object(1)
memory usage: 36.0+ MB
5
Column shape going into merge (654159, 3)
Joined shape going onto merge (673586, 7)
Joined shape after merge (673763, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673763 entries, 0 to 673762
Data columns (total 8 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        673763 non-null  object
 1   year                                         673763 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 41.1+ MB
6
Column shape going into merge (643360, 3)
Joined shape going onto merge (673763, 8)
Joined shape after merge (673763, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673763 entries, 0 to 673762
Data columns (total 9 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        673763 non-null  object
 1   year                                         673763 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
dtypes: float64(7), int64(1), object(1)
memory usage: 46.3+ MB
7
Column shape going into merge (602962, 3)
Joined shape going onto merge (673763, 9)
Joined shape after merge (674503, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 10 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 51.5+ MB
8
Column shape going into merge (567001, 3)
Joined shape going onto merge (674503, 10)
Joined shape after merge (674503, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 11 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
dtypes: float64(9), int64(1), object(1)
memory usage: 56.6+ MB
9

Column shape going into merge (558752, 3)
Joined shape going onto merge (674503, 11)
Joined shape after merge (674503, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 12 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
dtypes: float64(10), int64(1), object(1)
memory usage: 61.8+ MB
10
Column shape going into merge (546289, 3)
Joined shape going onto merge (674503, 12)
Joined shape after merge (674503, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 13 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
dtypes: float64(11), int64(1), object(1)
memory usage: 66.9+ MB
11
Column shape going into merge (545060, 3)
Joined shape going onto merge (674503, 13)
Joined shape after merge (674503, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 14 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
dtypes: float64(12), int64(1), object(1)
memory usage: 72.0+ MB
12
Column shape going into merge (541071, 3)
Joined shape going onto merge (674503, 14)
Joined shape after merge (674503, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 15 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
dtypes: float64(13), int64(1), object(1)
memory usage: 77.2+ MB
13
Column shape going into merge (455846, 3)
Joined shape going onto merge (674503, 15)
Joined shape after merge (674503, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 16 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
dtypes: float64(14), int64(1), object(1)
memory usage: 82.3+ MB
14
Column shape going into merge (453255, 3)
Joined shape going onto merge (674503, 16)
Joined shape after merge (674503, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 17 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
dtypes: float64(15), int64(1), object(1)
memory usage: 87.5+ MB
15

Column shape going into merge (446922, 3)
Joined shape going onto merge (674503, 17)
Joined shape after merge (674503, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674503 entries, 0 to 674502
Data columns (total 18 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674503 non-null  object
 1   year                                         674503 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
dtypes: float64(16), int64(1), object(1)
memory usage: 92.6+ MB
16
Column shape going into merge (439806, 3)
Joined shape going onto merge (674503, 18)
Joined shape after merge (674553, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674553 entries, 0 to 674552
Data columns (total 19 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674553 non-null  object
 1   year                                         674553 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
dtypes: float64(17), int64(1), object(1)
memory usage: 97.8+ MB
17
Column shape going into merge (423128, 3)
Joined shape going onto merge (674553, 19)
Joined shape after merge (674554, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674554 entries, 0 to 674553
Data columns (total 20 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674554 non-null  object
 1   year                                         674554 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
dtypes: float64(18), int64(1), object(1)
memory usage: 102.9+ MB
18
Column shape going into merge (422149, 3)
Joined shape going onto merge (674554, 20)
Joined shape after merge (674554, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674554 entries, 0 to 674553
Data columns (total 21 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674554 non-null  object
 1   year                                         674554 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
dtypes: float64(19), int64(1), object(1)
memory usage: 108.1+ MB
19
Column shape going into merge (408079, 3)
Joined shape going onto merge (674554, 21)
Joined shape after merge (674554, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674554 entries, 0 to 674553
Data columns (total 22 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674554 non-null  object
 1   year                                         674554 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
dtypes: float64(20), int64(1), object(1)
memory usage: 113.2+ MB
20

Column shape going into merge (377490, 3)
Joined shape going onto merge (674554, 22)
Joined shape after merge (674554, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674554 entries, 0 to 674553
Data columns (total 23 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        674554 non-null  object
 1   year                                         674554 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
dtypes: float64(21), int64(1), object(1)
memory usage: 118.4+ MB
21
Column shape going into merge (352473, 3)
Joined shape going onto merge (674554, 23)
Joined shape after merge (676998, 24)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 676998 entries, 0 to 676997
Data columns (total 24 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        676998 non-null  object
 1   year                                         676998 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
dtypes: float64(22), int64(1), object(1)
memory usage: 124.0+ MB
22
Column shape going into merge (326666, 3)
Joined shape going onto merge (676998, 24)
Joined shape after merge (676998, 25)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 676998 entries, 0 to 676997
Data columns (total 25 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        676998 non-null  object
 1   year                                         676998 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
 24  tangible_assets_th_gbp                       326666 non-null  float64
dtypes: float64(23), int64(1), object(1)
memory usage: 129.1+ MB
23
Column shape going into merge (292515, 3)
Joined shape going onto merge (676998, 25)
Joined shape after merge (677179, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677179 entries, 0 to 677178
Data columns (total 26 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        677179 non-null  object
 1   year                                         677179 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
 24  tangible_assets_th_gbp                       326666 non-null  float64
 25  ebitda_th_gbp                                292515 non-null  float64
dtypes: float64(24), int64(1), object(1)
memory usage: 134.3+ MB
24

Column shape going into merge (292515, 3)
Joined shape going onto merge (677179, 26)
Joined shape after merge (677179, 27)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677179 entries, 0 to 677178
Data columns (total 27 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        677179 non-null  object
 1   year                                         677179 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
 24  tangible_assets_th_gbp                       326666 non-null  float64
 25  ebitda_th_gbp                                292515 non-null  float64
 26  operating_profit_th_gbp                      292515 non-null  float64
dtypes: float64(25), int64(1), object(1)
memory usage: 139.5+ MB
25
Column shape going into merge (290047, 3)
Joined shape going onto merge (677179, 27)
Joined shape after merge (677187, 28)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677187 entries, 0 to 677186
Data columns (total 28 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        677187 non-null  object
 1   year                                         677187 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
 24  tangible_assets_th_gbp                       326666 non-null  float64
 25  ebitda_th_gbp                                292515 non-null  float64
 26  operating_profit_th_gbp                      292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp    290047 non-null  float64
dtypes: float64(26), int64(1), object(1)
memory usage: 144.7+ MB
26
Column shape going into merge (288308, 3)
Joined shape going onto merge (677187, 28)
Joined shape after merge (677191, 29)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677191 entries, 0 to 677190
Data columns (total 29 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        677191 non-null  object
 1   year                                         677191 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
 24  tangible_assets_th_gbp                       326666 non-null  float64
 25  ebitda_th_gbp                                292515 non-null  float64
 26  operating_profit_th_gbp                      292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp    290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp               288308 non-null  float64
dtypes: float64(27), int64(1), object(1)
memory usage: 149.8+ MB
27
Column shape going into merge (287782, 3)
Joined shape going onto merge (677191, 29)
Joined shape after merge (677191, 30)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677191 entries, 0 to 677190
Data columns (total 30 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        677191 non-null  object
 1   year                                         677191 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
 24  tangible_assets_th_gbp                       326666 non-null  float64
 25  ebitda_th_gbp                                292515 non-null  float64
 26  operating_profit_th_gbp                      292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp    290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp               288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp              287782 non-null  float64
dtypes: float64(28), int64(1), object(1)
memory usage: 155.0+ MB
28

Column shape going into merge (287782, 3)
Joined shape going onto merge (677191, 30)
Joined shape after merge (677191, 31)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677191 entries, 0 to 677190
Data columns (total 31 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   bv_id                                        677191 non-null  object
 1   year                                         677191 non-null  int64
 2   total_assets_less_cur._liab._th_gbp          672445 non-null  float64
 3   net_assets_th_gbp                            669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp           668381 non-null  float64
 5   total_assets_th_gbp                          664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp  659341 non-null  float64
 7   shareholders_funds_th_gbp                    654159 non-null  float64
 8   current_assets_th_gbp                        643360 non-null  float64
 9   total_reserves_th_gbp                        602962 non-null  float64
 10  current_liabilities_th_gbp                   567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)             558752 non-null  float64
 12  current_ratio_(x)                            546289 non-null  float64
 13  liquidity_ratio_(x)                          545060 non-null  float64
 14  total_other_current_liabilities_th_gbp       541071 non-null  float64
 15  other_current_assets_th_gbp                  455846 non-null  float64
 16  bank_&_deposits_th_gbp                       453255 non-null  float64
 17  other_current_liabilities_th_gbp             446922 non-null  float64
 18  profit_(loss)_account_th_gbp                 439806 non-null  float64
 19  issued_capital_th_gbp                        423128 non-null  float64
 20  ordinary_shares_th_gbp                       422149 non-null  float64
 21  other_debtors_th_gbp                         408079 non-null  float64
 22  fixed_assets_th_gbp                          377490 non-null  float64
 23  turnover_th_gbp                              352473 non-null  float64
 24  tangible_assets_th_gbp                       326666 non-null  float64
 25  ebitda_th_gbp                                292515 non-null  float64
 26  operating_profit_th_gbp                      292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp    290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp               288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp              287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp         287782 non-null  float64
dtypes: float64(29), int64(1), object(1)
memory usage: 160.2+ MB
29
Column shape going into merge (287500, 3)
Joined shape going onto merge (677191, 31)
Joined shape after merge (677191, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677191 entries, 0 to 677190
Data columns (total 32 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677191 non-null  object
 1   year                                           677191 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
dtypes: float64(30), int64(1), object(1)
memory usage: 165.3+ MB
30
Column shape going into merge (285109, 3)
Joined shape going onto merge (677191, 32)
Joined shape after merge (677191, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677191 entries, 0 to 677190
Data columns (total 33 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677191 non-null  object
 1   year                                           677191 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
dtypes: float64(31), int64(1), object(1)
memory usage: 170.5+ MB
31

Column shape going into merge (281767, 3)
Joined shape going onto merge (677191, 33)
Joined shape after merge (677203, 34)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 34 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
dtypes: float64(32), int64(1), object(1)
memory usage: 175.7+ MB
32
Column shape going into merge (268831, 3)
Joined shape going onto merge (677203, 34)
Joined shape after merge (677203, 35)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 35 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
dtypes: float64(33), int64(1), object(1)
memory usage: 180.8+ MB
33
Column shape going into merge (255321, 3)
Joined shape going onto merge (677203, 35)
Joined shape after merge (677203, 36)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 36 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
dtypes: float64(34), int64(1), object(1)
memory usage: 186.0+ MB
34

Column shape going into merge (249889, 3)
Joined shape going onto merge (677203, 36)
Joined shape after merge (677203, 37)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 37 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
dtypes: float64(35), int64(1), object(1)
memory usage: 191.2+ MB
35
Column shape going into merge (244969, 3)
Joined shape going onto merge (677203, 37)
Joined shape after merge (677203, 38)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 38 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
dtypes: float64(36), int64(1), object(1)
memory usage: 196.3+ MB
36
Column shape going into merge (244969, 3)
Joined shape going onto merge (677203, 38)
Joined shape after merge (677203, 39)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 39 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
dtypes: float64(37), int64(1), object(1)
memory usage: 201.5+ MB
37

Column shape going into merge (242782, 3)
Joined shape going onto merge (677203, 39)
Joined shape after merge (677203, 40)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 40 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
dtypes: float64(38), int64(1), object(1)
memory usage: 206.7+ MB
38
Column shape going into merge (242782, 3)
Joined shape going onto merge (677203, 40)
Joined shape after merge (677203, 41)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 41 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
dtypes: float64(39), int64(1), object(1)
memory usage: 211.8+ MB
39
Column shape going into merge (235333, 3)
Joined shape going onto merge (677203, 41)
Joined shape after merge (677203, 42)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 42 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
dtypes: float64(40), int64(1), object(1)
memory usage: 217.0+ MB
40
Column shape going into merge (228429, 3)
Joined shape going onto merge (677203, 42)

Joined shape after merge (677203, 43)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677203 entries, 0 to 677202
Data columns (total 43 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677203 non-null  object
 1   year                                           677203 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
dtypes: float64(41), int64(1), object(1)
memory usage: 222.2+ MB
41
Column shape going into merge (227942, 3)
Joined shape going onto merge (677203, 43)
Joined shape after merge (677211, 44)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677211 entries, 0 to 677210
Data columns (total 44 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677211 non-null  object
 1   year                                           677211 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
dtypes: float64(42), int64(1), object(1)
memory usage: 227.3+ MB
42
Column shape going into merge (219303, 3)
Joined shape going onto merge (677211, 44)
Joined shape after merge (677259, 45)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 45 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
dtypes: float64(43), int64(1), object(1)
memory usage: 232.5+ MB
43
Column shape going into merge (200887, 3)
Joined shape going onto merge (677259, 45)

Joined shape after merge (677259, 46)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 46 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
dtypes: float64(44), int64(1), object(1)
memory usage: 237.7+ MB
44
Column shape going into merge (198698, 3)
Joined shape going onto merge (677259, 46)
Joined shape after merge (677259, 47)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 47 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
dtypes: float64(45), int64(1), object(1)
memory usage: 242.9+ MB
45
Column shape going into merge (177963, 3)
Joined shape going onto merge (677259, 47)
Joined shape after merge (677259, 48)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 48 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
dtypes: float64(46), int64(1), object(1)
memory usage: 248.0+ MB
46
Column shape going into merge (176670, 3)
Joined shape going onto merge (677259, 48)

Joined shape after merge (677259, 49)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 49 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
dtypes: float64(47), int64(1), object(1)
memory usage: 253.2+ MB
47
Column shape going into merge (153437, 3)
Joined shape going onto merge (677259, 49)
Joined shape after merge (677259, 50)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 50 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
dtypes: float64(48), int64(1), object(1)
memory usage: 258.4+ MB
48
Column shape going into merge (150498, 3)
Joined shape going onto merge (677259, 50)

Joined shape after merge (677259, 51)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 51 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
dtypes: float64(49), int64(1), object(1)
memory usage: 263.5+ MB
49
Column shape going into merge (146331, 3)
Joined shape going onto merge (677259, 51)
Joined shape after merge (677259, 52)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 52 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
dtypes: float64(50), int64(1), object(1)
memory usage: 268.7+ MB
50
Column shape going into merge (145736, 3)
Joined shape going onto merge (677259, 52)

Joined shape after merge (677259, 53)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 53 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
dtypes: float64(51), int64(1), object(1)
memory usage: 273.9+ MB
51
Column shape going into merge (139658, 3)
Joined shape going onto merge (677259, 53)
Joined shape after merge (677259, 54)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 54 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
dtypes: float64(52), int64(1), object(1)
memory usage: 279.0+ MB
52
Column shape going into merge (139658, 3)
Joined shape going onto merge (677259, 54)

Joined shape after merge (677259, 55)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 55 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
dtypes: float64(53), int64(1), object(1)
memory usage: 284.2+ MB
53
Column shape going into merge (136910, 3)
Joined shape going onto merge (677259, 55)
Joined shape after merge (677259, 56)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 56 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
dtypes: float64(54), int64(1), object(1)
memory usage: 289.4+ MB
54
Column shape going into merge (136167, 3)
Joined shape going onto merge (677259, 56)

Joined shape after merge (677259, 57)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 57 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
dtypes: float64(55), int64(1), object(1)
memory usage: 294.5+ MB
55
Column shape going into merge (134113, 3)
Joined shape going onto merge (677259, 57)
Joined shape after merge (677259, 58)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 58 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
dtypes: float64(56), int64(1), object(1)
memory usage: 299.7+ MB
56
Column shape going into merge (126882, 3)
Joined shape going onto merge (677259, 58)

Joined shape after merge (677259, 59)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 59 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
dtypes: float64(57), int64(1), object(1)
memory usage: 304.9+ MB
57
Column shape going into merge (126033, 3)
Joined shape going onto merge (677259, 59)
Joined shape after merge (677259, 60)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 60 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
dtypes: float64(58), int64(1), object(1)
memory usage: 310.0+ MB
58
Column shape going into merge (118001, 3)
Joined shape going onto merge (677259, 60)

Joined shape after merge (677259, 61)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 61 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
dtypes: float64(59), int64(1), object(1)
memory usage: 315.2+ MB
59
Column shape going into merge (117577, 3)
Joined shape going onto merge (677259, 61)
Joined shape after merge (677259, 62)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 62 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
dtypes: float64(60), int64(1), object(1)
memory usage: 320.4+ MB
60
Column shape going into merge (114323, 3)
Joined shape going onto merge (677259, 62)

Joined shape after merge (677259, 63)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 63 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
dtypes: float64(61), int64(1), object(1)
memory usage: 325.5+ MB
61
Column shape going into merge (112825, 3)
Joined shape going onto merge (677259, 63)
Joined shape after merge (677259, 64)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 64 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
dtypes: float64(62), int64(1), object(1)
memory usage: 330.7+ MB
62
Column shape going into merge (107431, 3)
Joined shape going onto merge (677259, 64)

Joined shape after merge (677259, 65)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 65 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
dtypes: float64(63), int64(1), object(1)
memory usage: 335.9+ MB
63
Column shape going into merge (94781, 3)
Joined shape going onto merge (677259, 65)
Joined shape after merge (677259, 66)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 66 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
dtypes: float64(64), int64(1), object(1)
memory usage: 341.0+ MB
64
Column shape going into merge (93166, 3)
Joined shape going onto merge (677259, 66)

Joined shape after merge (677259, 67)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 67 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
dtypes: float64(65), int64(1), object(1)
memory usage: 346.2+ MB
65
Column shape going into merge (89839, 3)
Joined shape going onto merge (677259, 67)
Joined shape after merge (677259, 68)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 68 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
dtypes: float64(66), int64(1), object(1)
memory usage: 351.4+ MB
66
Column shape going into merge (88780, 3)
Joined shape going onto merge (677259, 68)

Joined shape after merge (677259, 69)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 69 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
dtypes: float64(67), int64(1), object(1)
memory usage: 356.5+ MB
67
Column shape going into merge (87867, 3)
Joined shape going onto merge (677259, 69)
Joined shape after merge (677259, 70)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677259 entries, 0 to 677258
Data columns (total 70 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677259 non-null  object
 1   year                                           677259 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
dtypes: float64(68), int64(1), object(1)
memory usage: 361.7+ MB
68
Column shape going into merge (86521, 3)
Joined shape going onto merge (677259, 70)

Joined shape after merge (677261, 71)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 71 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
dtypes: float64(69), int64(1), object(1)
memory usage: 366.9+ MB
69
Column shape going into merge (85935, 3)
Joined shape going onto merge (677261, 71)
Joined shape after merge (677261, 72)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 72 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
dtypes: float64(70), int64(1), object(1)
memory usage: 372.0+ MB
70
Column shape going into merge (84842, 3)
Joined shape going onto merge (677261, 72)

Joined shape after merge (677261, 73)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 73 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
dtypes: float64(71), int64(1), object(1)
memory usage: 377.2+ MB
71
Column shape going into merge (81429, 3)
Joined shape going onto merge (677261, 73)
Joined shape after merge (677261, 74)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 74 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
dtypes: float64(72), int64(1), object(1)
memory usage: 382.4+ MB
72
Column shape going into merge (79266, 3)
Joined shape going onto merge (677261, 74)

Joined shape after merge (677261, 75)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 75 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
dtypes: float64(73), int64(1), object(1)
memory usage: 387.5+ MB
73
Column shape going into merge (77279, 3)
Joined shape going onto merge (677261, 75)
Joined shape after merge (677261, 76)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 76 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
dtypes: float64(74), int64(1), object(1)
memory usage: 392.7+ MB
74
Column shape going into merge (76851, 3)
Joined shape going onto merge (677261, 76)

Joined shape after merge (677261, 77)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 77 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
dtypes: float64(75), int64(1), object(1)
memory usage: 397.9+ MB
75
Column shape going into merge (76547, 3)
Joined shape going onto merge (677261, 77)
Joined shape after merge (677261, 78)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 78 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
dtypes: float64(76), int64(1), object(1)
memory usage: 403.0+ MB
76
Column shape going into merge (76335, 3)
Joined shape going onto merge (677261, 78)

Joined shape after merge (677261, 79)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 79 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
dtypes: float64(77), int64(1), object(1)
memory usage: 408.2+ MB
77
Column shape going into merge (76153, 3)
Joined shape going onto merge (677261, 79)
Joined shape after merge (677261, 80)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677261 entries, 0 to 677260
Data columns (total 80 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677261 non-null  object
 1   year                                           677261 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
dtypes: float64(78), int64(1), object(1)
memory usage: 413.4+ MB
78
Column shape going into merge (74680, 3)
Joined shape going onto merge (677261, 80)

Joined shape after merge (677263, 81)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 81 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
dtypes: float64(79), int64(1), object(1)
memory usage: 418.5+ MB
79
Column shape going into merge (73098, 3)
Joined shape going onto merge (677263, 81)
Joined shape after merge (677263, 82)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 82 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
dtypes: float64(80), int64(1), object(1)
memory usage: 423.7+ MB
80
Column shape going into merge (72909, 3)
Joined shape going onto merge (677263, 82)

Joined shape after merge (677263, 83)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 83 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
dtypes: float64(81), int64(1), object(1)
memory usage: 428.9+ MB
81
Column shape going into merge (68709, 3)
Joined shape going onto merge (677263, 83)
Joined shape after merge (677263, 84)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 84 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
dtypes: float64(82), int64(1), object(1)
memory usage: 434.0+ MB
82
Column shape going into merge (64944, 3)
Joined shape going onto merge (677263, 84)

Joined shape after merge (677263, 85)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 85 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
dtypes: float64(83), int64(1), object(1)
memory usage: 439.2+ MB
83
Column shape going into merge (64657, 3)
Joined shape going onto merge (677263, 85)
Joined shape after merge (677263, 86)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 86 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
dtypes: float64(84), int64(1), object(1)
memory usage: 444.4+ MB
84
Column shape going into merge (64406, 3)
Joined shape going onto merge (677263, 86)

Joined shape after merge (677263, 87)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 87 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
dtypes: float64(85), int64(1), object(1)
memory usage: 449.5+ MB
85
Column shape going into merge (64224, 3)
Joined shape going onto merge (677263, 87)
Joined shape after merge (677263, 88)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 88 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
dtypes: float64(86), int64(1), object(1)
memory usage: 454.7+ MB
86
Column shape going into merge (63213, 3)
Joined shape going onto merge (677263, 88)

Joined shape after merge (677263, 89)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 89 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
dtypes: float64(87), int64(1), object(1)
memory usage: 459.9+ MB
87
Column shape going into merge (62139, 3)
Joined shape going onto merge (677263, 89)
Joined shape after merge (677263, 90)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 90 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
dtypes: float64(88), int64(1), object(1)
memory usage: 465.0+ MB
88
Column shape going into merge (59167, 3)
Joined shape going onto merge (677263, 90)

Joined shape after merge (677263, 91)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 91 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
dtypes: float64(89), int64(1), object(1)
memory usage: 470.2+ MB
89
Column shape going into merge (57933, 3)
Joined shape going onto merge (677263, 91)
Joined shape after merge (677263, 92)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 92 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
dtypes: float64(90), int64(1), object(1)
memory usage: 475.4+ MB
90
Column shape going into merge (57503, 3)
Joined shape going onto merge (677263, 92)

Joined shape after merge (677263, 93)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 93 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
dtypes: float64(91), int64(1), object(1)
memory usage: 480.5+ MB
91
Column shape going into merge (54531, 3)
Joined shape going onto merge (677263, 93)
Joined shape after merge (677263, 94)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677263 entries, 0 to 677262
Data columns (total 94 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677263 non-null  object
 1   year                                           677263 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
 93  total_other_income_&_int._received_th_gbp      54531 non-null   float64
dtypes: float64(92), int64(1), object(1)
memory usage: 485.7+ MB
92
Column shape going into merge (51990, 3)
Joined shape going onto merge (677263, 94)

Joined shape after merge (677264, 95)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Data columns (total 95 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677264 non-null  object
 1   year                                           677264 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
 93  total_other_income_&_int._received_th_gbp      54531 non-null   float64
 94  audit_fee_th_gbp                               51990 non-null   float64
dtypes: float64(93), int64(1), object(1)
memory usage: 490.9+ MB
93
Column shape going into merge (51199, 3)
Joined shape going onto merge (677264, 95)
Joined shape after merge (677264, 96)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Data columns (total 96 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677264 non-null  object
 1   year                                           677264 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
 93  total_other_income_&_int._received_th_gbp      54531 non-null   float64
 94  audit_fee_th_gbp                               51990 non-null   float64
 95  interest_cover_(x)                             51199 non-null   float64
dtypes: float64(94), int64(1), object(1)
memory usage: 496.0+ MB
94
Column shape going into merge (49084, 3)
Joined shape going onto merge (677264, 96)

Joined shape after merge (677264, 97)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Data columns (total 97 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677264 non-null  object
 1   year                                           677264 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
 93  total_other_income_&_int._received_th_gbp      54531 non-null   float64
 94  audit_fee_th_gbp                               51990 non-null   float64
 95  interest_cover_(x)                             51199 non-null   float64
 96  non-tax_advisory_services_th_gbp               49084 non-null   float64
dtypes: float64(95), int64(1), object(1)
memory usage: 501.2+ MB
95
Column shape going into merge (48796, 3)
Joined shape going onto merge (677264, 97)
Joined shape after merge (677264, 98)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Data columns (total 98 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677264 non-null  object
 1   year                                           677264 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
 93  total_other_income_&_int._received_th_gbp      54531 non-null   float64
 94  audit_fee_th_gbp                               51990 non-null   float64
 95  interest_cover_(x)                             51199 non-null   float64
 96  non-tax_advisory_services_th_gbp               49084 non-null   float64
 97  other_interest_paid_th_gbp                     48796 non-null   float64
dtypes: float64(96), int64(1), object(1)
memory usage: 506.4+ MB
96
Column shape going into merge (48099, 3)
Joined shape going onto merge (677264, 98)

Joined shape after merge (677264, 99)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Data columns (total 99 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677264 non-null  object
 1   year                                           677264 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
 93  total_other_income_&_int._received_th_gbp      54531 non-null   float64
 94  audit_fee_th_gbp                               51990 non-null   float64
 95  interest_cover_(x)                             51199 non-null   float64
 96  non-tax_advisory_services_th_gbp               49084 non-null   float64
 97  other_interest_paid_th_gbp                     48796 non-null   float64
 98  provisions_for_other_liab._th_gbp              48099 non-null   float64
dtypes: float64(97), int64(1), object(1)
memory usage: 511.5+ MB
97
Column shape going into merge (45727, 3)
Joined shape going onto merge (677264, 99)
Joined shape after merge (677264, 100)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Data columns (total 100 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   bv_id                                          677264 non-null  object
 1   year                                           677264 non-null  int64
 2   total_assets_less_cur._liab._th_gbp            672445 non-null  float64
 3   net_assets_th_gbp                              669538 non-null  float64
 4   net_tangible_assets_(liab.)_th_gbp             668381 non-null  float64
 5   total_assets_th_gbp                            664023 non-null  float64
 6   net_current_assets_(working_capital)_th_gbp    659341 non-null  float64
 7   shareholders_funds_th_gbp                      654159 non-null  float64
 8   current_assets_th_gbp                          643360 non-null  float64
 9   total_reserves_th_gbp                          602962 non-null  float64
 10  current_liabilities_th_gbp                     567001 non-null  float64
 11  solvency_ratio_(asset_based)_(%)               558752 non-null  float64
 12  current_ratio_(x)                              546289 non-null  float64
 13  liquidity_ratio_(x)                            545060 non-null  float64
 14  total_other_current_liabilities_th_gbp         541071 non-null  float64
 15  other_current_assets_th_gbp                    455846 non-null  float64
 16  bank_&_deposits_th_gbp                         453255 non-null  float64
 17  other_current_liabilities_th_gbp               446922 non-null  float64
 18  profit_(loss)_account_th_gbp                   439806 non-null  float64
 19  issued_capital_th_gbp                          423128 non-null  float64
 20  ordinary_shares_th_gbp                         422149 non-null  float64
 21  other_debtors_th_gbp                           408079 non-null  float64
 22  fixed_assets_th_gbp                            377490 non-null  float64
 23  turnover_th_gbp                                352473 non-null  float64
 24  tangible_assets_th_gbp                         326666 non-null  float64
 25  ebitda_th_gbp                                  292515 non-null  float64
 26  operating_profit_th_gbp                        292515 non-null  float64
 27  profit_(loss)_before_interest_paid_th_gbp      290047 non-null  float64
 28  profit_(loss)_after_tax_th_gbp                 288308 non-null  float64
 29  profit_(loss)_before_tax_th_gbp                287782 non-null  float64
 30  profit_(loss)_before_taxation_th_gbp           287782 non-null  float64
 31  profit_(loss)_for_period_[=net_income]_th_gbp  287500 non-null  float64
 32  retained_profit(loss)_th_gbp                   285109 non-null  float64
 33  administration_expenses_th_gbp                 281767 non-null  float64
 34  return_on_total_assets_(%)                     268831 non-null  float64
 35  solvency_ratio_(liability_based)_(%)           255321 non-null  float64
 36  ebit_margin_(%)                                249889 non-null  float64
 37  return_on_capital_employed                     244969 non-null  float64
 38  return_on_capital_employed_(%)                 244969 non-null  float64
 39  profit_margin                                  242782 non-null  float64
 40  profit_margin_(%)                              242782 non-null  float64
 41  other_fixed_assets_th_gbp                      235333 non-null  float64
 42  working_capital_needs_th_gbp                   228429 non-null  float64
 43  depreciation_th_gbp                            227942 non-null  float64
 44  number_of_employees                            219303 non-null  float64
 45  long_term_liabilities_th_gbp                   200887 non-null  float64
 46  net_assets_turnover_(x)                        198698 non-null  float64
 47  shareholders_liquidity_ratio_(x)               177963 non-null  float64
 48  other_reserves_th_gbp                          176670 non-null  float64
 49  gross_profit_th_gbp                            153437 non-null  float64
 50  fixed_assets_turnover_(x)                      150498 non-null  float64
 51  gross_margin_(%)                               146331 non-null  float64
 52  berry_ratio_(x)                                145736 non-null  float64
 53  return_on_shareholders_funds                   139658 non-null  float64
 54  return_on_shareholders_funds_(%)               139658 non-null  float64
 55  short_term_loans_&_overdrafts_th_gbp           136910 non-null  float64
 56  trade_creditors_th_gbp                         136167 non-null  float64
 57  taxation_th_gbp                                134113 non-null  float64
 58  trade_debtors_th_gbp                           126882 non-null  float64
 59  cost_of_sales_th_gbp                           126033 non-null  float64
 60  social_securities_&_v.a.t._th_gbp              118001 non-null  float64
 61  accruals_&_def._inc._(short_t.)_th_gbp         117577 non-null  float64
 62  ebitda_margin_(%)                              114323 non-null  float64
 63  total_other_long_term_liab._th_gbp             112825 non-null  float64
 64  gearing_(%)                                    107431 non-null  float64
 65  stock_&_w.i.p._th_gbp                          94781 non-null   float64
 66  creditors_payment_(days)                       93166 non-null   float64
 67  other_long_term_liab._th_gbp                   89839 non-null   float64
 68  debtor_collection_(days)                       88780 non-null   float64
 69  debtors_turnover_(x)                           87867 non-null   float64
 70  remuneration_th_gbp                            86521 non-null   float64
 71  wages_&_salaries_th_gbp                        85935 non-null   float64
 72  depreciation_other_assets_th_gbp               84842 non-null   float64
 73  stock_th_gbp                                   81429 non-null   float64
 74  shareholders_funds_per_employee_(unit)_gbp     79266 non-null   float64
 75  corporation_tax_th_gbp                         77279 non-null   float64
 76  salaries/turnover                              76851 non-null   float64
 77  turnover_per_employee_(unit)_gbp               76547 non-null   float64
 78  working_capital_per_employee_(unit)_gbp        76335 non-null   float64
 79  profit_per_employee_(unit)_gbp                 76153 non-null   float64
 80  net_interest_th_gbp                            74680 non-null   float64
 81  plant_&_vehicles_th_gbp                        73098 non-null   float64
 82  prepayments_th_gbp                             72909 non-null   float64
 83  other_operating_income/costs_pre_op_th_gbp     68709 non-null   float64
 84  long_term_debt_th_gbp                          64944 non-null   float64
 85  investments_th_gbp                             64657 non-null   float64
 86  directors'_remuneration_th_gbp                 64406 non-null   float64
 87  asset_cover_(x)                                64224 non-null   float64
 88  directors'_fees_th_gbp                         63213 non-null   float64
 89  group_loans_(short_t.)_th_gbp                  62139 non-null   float64
 90  plant_th_gbp                                   59167 non-null   float64
 91  interest_paid_th_gbp                           57933 non-null   float64
 92  non-audit_fee_th_gbp                           57503 non-null   float64
 93  total_other_income_&_int._received_th_gbp      54531 non-null   float64
 94  audit_fee_th_gbp                               51990 non-null   float64
 95  interest_cover_(x)                             51199 non-null   float64
 96  non-tax_advisory_services_th_gbp               49084 non-null   float64
 97  other_interest_paid_th_gbp                     48796 non-null   float64
 98  provisions_for_other_liab._th_gbp              48099 non-null   float64
 99  average_remuneration_per_employee_(unit)_gbp   45727 non-null   float64
dtypes: float64(98), int64(1), object(1)
memory usage: 516.7+ MB
98
Column shape going into merge (44945, 3)
Joined shape going onto merge (677264, 100)

Joined shape after merge (677264, 101)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 101 entries, bv_id to group_loans_(asset)_th_gbp
dtypes: float64(99), int64(1), object(1)
memory usage: 521.9+ MB
99
Column shape going into merge (44721, 3)
Joined shape going onto merge (677264, 101)
Joined shape after merge (677264, 102)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 102 entries, bv_id to national_turnover_th_gbp
dtypes: float64(100), int64(1), object(1)
memory usage: 527.0+ MB
100
Column shape going into merge (42342, 3)
Joined shape going onto merge (677264, 102)
Joined shape after merge (677264, 103)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 103 entries, bv_id to interest_received_th_gbp
dtypes: float64(101), int64(1), object(1)
memory usage: 532.2+ MB
101
Column shape going into merge (40379, 3)
Joined shape going onto merge (677264, 103)
Joined shape after merge (677264, 104)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 104 entries, bv_id to intangible_assets_th_gbp
dtypes: float64(102), int64(1), object(1)
memory usage: 537.4+ MB
102
Column shape going into merge (40291, 3)
Joined shape going onto merge (677264, 104)
Joined shape after merge (677264, 105)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 105 entries, bv_id to stock_turnover_(x)
dtypes: float64(103), int64(1), object(1)
memory usage: 542.5+ MB
103
Column shape going into merge (37956, 3)
Joined shape going onto merge (677264, 105)
Joined shape after merge (677264, 106)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 106 entries, bv_id to director_loans_(short_t.)_th_gbp
dtypes: float64(104), int64(1), object(1)
memory usage: 547.7+ MB
104
Column shape going into merge (36944, 3)
Joined shape going onto merge (677264, 106)
Joined shape after merge (677264, 107)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 107 entries, bv_id to fixtures_&_fittings_th_gbp
dtypes: float64(105), int64(1), object(1)
memory usage: 552.9+ MB
105
Column shape going into merge (36617, 3)
Joined shape going onto merge (677264, 107)
Joined shape after merge (677264, 108)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 108 entries, bv_id to depreciation_owned_assets_th_gbp
dtypes: float64(106), int64(1), object(1)
memory usage: 558.0+ MB
106
Column shape going into merge (34819, 3)
Joined shape going onto merge (677264, 108)
Joined shape after merge (677264, 109)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 109 entries, bv_id to bank_overdrafts_th_gbp
dtypes: float64(107), int64(1), object(1)
memory usage: 563.2+ MB
107
Column shape going into merge (32514, 3)
Joined shape going onto merge (677264, 109)
Joined shape after merge (677264, 110)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677264 entries, 0 to 677263
Columns: 110 entries, bv_id to other_provisions_th_gbp
dtypes: float64(108), int64(1), object(1)
memory usage: 568.4+ MB
108
Column shape going into merge (31244, 3)
Joined shape going onto merge (677264, 110)
Joined shape after merge (677267, 111)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677267 entries, 0 to 677266
Columns: 111 entries, bv_id to cash_in(out)flow_operat._activ._th_gbp
dtypes: float64(109), int64(1), object(1)
memory usage: 573.6+ MB
109
Column shape going into merge (30797, 3)
Joined shape going onto merge (677267, 111)
Joined shape after merge (677267, 112)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677267 entries, 0 to 677266
Columns: 112 entries, bv_id to social_security_costs_th_gbp
dtypes: float64(110), int64(1), object(1)
memory usage: 578.7+ MB
110
Column shape going into merge (29497, 3)
Joined shape going onto merge (677267, 112)
Joined shape after merge (677268, 113)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 113 entries, bv_id to increase(decrease)_cash_&_equiv._th_gbp
dtypes: float64(111), int64(1), object(1)
memory usage: 583.9+ MB
111
Column shape going into merge (28961, 3)
Joined shape going onto merge (677268, 113)
Joined shape after merge (677268, 114)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 114 entries, bv_id to accruals_&_def._inc._(long_t.)_th_gbp
dtypes: float64(112), int64(1), object(1)
memory usage: 589.1+ MB
112
Column shape going into merge (28647, 3)
Joined shape going onto merge (677268, 114)
Joined shape after merge (677268, 115)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 115 entries, bv_id to deferred_taxation_th_gbp
dtypes: float64(113), int64(1), object(1)
memory usage: 594.2+ MB
113
Column shape going into merge (28290, 3)
Joined shape going onto merge (677268, 115)
Joined shape after merge (677268, 116)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 116 entries, bv_id to total_amortization_and_impairment_th_gbp
dtypes: float64(114), int64(1), object(1)
memory usage: 599.4+ MB
114
Column shape going into merge (27001, 3)
Joined shape going onto merge (677268, 116)
Joined shape after merge (677268, 117)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 117 entries, bv_id to other_long_term_loans_th_gbp
dtypes: float64(115), int64(1), object(1)
memory usage: 604.6+ MB
115
Column shape going into merge (25489, 3)
Joined shape going onto merge (677268, 117)
Joined shape after merge (677268, 118)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 118 entries, bv_id to land_&_buildings_th_gbp
dtypes: float64(116), int64(1), object(1)
memory usage: 609.7+ MB
116
Column shape going into merge (23420, 3)
Joined shape going onto merge (677268, 118)
Joined shape after merge (677268, 119)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 119 entries, bv_id to vehicles_th_gbp
dtypes: float64(117), int64(1), object(1)
memory usage: 614.9+ MB
117
Column shape going into merge (23191, 3)
Joined shape going onto merge (677268, 119)
Joined shape after merge (677268, 120)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 120 entries, bv_id to director_loans_(long_t.)_th_gbp
dtypes: float64(118), int64(1), object(1)
memory usage: 620.1+ MB
118
Column shape going into merge (18628, 3)
Joined shape going onto merge (677268, 120)
Joined shape after merge (677268, 121)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 121 entries, bv_id to other_income_th_gbp
dtypes: float64(119), int64(1), object(1)
memory usage: 625.2+ MB
119
Column shape going into merge (18271, 3)
Joined shape going onto merge (677268, 121)
Joined shape after merge (677268, 122)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 122 entries, bv_id to other_short_term_loans_th_gbp
dtypes: float64(120), int64(1), object(1)
memory usage: 630.4+ MB
120
Column shape going into merge (18056, 3)
Joined shape going onto merge (677268, 122)
Joined shape after merge (677268, 123)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 123 entries, bv_id to pension_costs_th_gbp
dtypes: float64(121), int64(1), object(1)
memory usage: 635.6+ MB
121
Column shape going into merge (17999, 3)
Joined shape going onto merge (677268, 123)
Joined shape after merge (677268, 124)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 124 entries, bv_id to cash_out(in)flow_from_financing_th_gbp
dtypes: float64(122), int64(1), object(1)
memory usage: 640.7+ MB
122
Column shape going into merge (16914, 3)
Joined shape going onto merge (677268, 124)
Joined shape after merge (677268, 125)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 125 entries, bv_id to freehold_land_th_gbp
dtypes: float64(123), int64(1), object(1)
memory usage: 645.9+ MB
123
Column shape going into merge (16587, 3)
Joined shape going onto merge (677268, 125)

Joined shape after merge (677268, 126)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 126 entries, bv_id to deferred_tax_th_gbp
dtypes: float64(124), int64(1), object(1)
memory usage: 651.1+ MB
124
Column shape going into merge (16439, 3)
Joined shape going onto merge (677268, 126)
Joined shape after merge (677268, 127)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 127 entries, bv_id to amortisation_th_gbp
dtypes: float64(125), int64(1), object(1)
memory usage: 656.2+ MB
125
Column shape going into merge (16111, 3)
Joined shape going onto merge (677268, 127)
Joined shape after merge (677268, 128)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 128 entries, bv_id to group_loans_(long_t.)_th_gbp
dtypes: float64(126), int64(1), object(1)
memory usage: 661.4+ MB
126
Column shape going into merge (15580, 3)
Joined shape going onto merge (677268, 128)
Joined shape after merge (677268, 129)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 129 entries, bv_id to total_operating_lease_rentals_th_gbp
dtypes: float64(127), int64(1), object(1)
memory usage: 666.6+ MB
127
Column shape going into merge (13314, 3)
Joined shape going onto merge (677268, 129)
Joined shape after merge (677268, 130)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 130 entries, bv_id to capital_expenditure_&_financ._invest._th_gbp
dtypes: float64(128), int64(1), object(1)
memory usage: 671.7+ MB
128
Column shape going into merge (12740, 3)
Joined shape going onto merge (677268, 130)
Joined shape after merge (677268, 131)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 131 entries, bv_id to foreign_exchange_gains/losses_th_gbp
dtypes: float64(129), int64(1), object(1)
memory usage: 676.9+ MB
129
Column shape going into merge (11683, 3)
Joined shape going onto merge (677268, 131)
Joined shape after merge (677268, 132)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 132 entries, bv_id to paid_to_bank_th_gbp
dtypes: float64(130), int64(1), object(1)
memory usage: 682.1+ MB
130
Column shape going into merge (11155, 3)
Joined shape going onto merge (677268, 132)
Joined shape after merge (677268, 133)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 133 entries, bv_id to share_premium_account_th_gbp
dtypes: float64(131), int64(1), object(1)
memory usage: 687.2+ MB
131
Column shape going into merge (10981, 3)
Joined shape going onto merge (677268, 133)
Joined shape after merge (677268, 134)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 134 entries, bv_id to cash_in(out)flow_ret._on_invest._th_gbp
dtypes: float64(132), int64(1), object(1)
memory usage: 692.4+ MB
132
Column shape going into merge (9463, 3)
Joined shape going onto merge (677268, 134)
Joined shape after merge (677268, 135)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 135 entries, bv_id to leasehold_land_th_gbp
dtypes: float64(133), int64(1), object(1)
memory usage: 697.6+ MB
133
Column shape going into merge (9233, 3)
Joined shape going onto merge (677268, 135)
Joined shape after merge (677268, 136)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 136 entries, bv_id to hire_purch._&_leas._(short_t.)_th_gbp
dtypes: float64(134), int64(1), object(1)
memory usage: 702.7+ MB
134
Column shape going into merge (7888, 3)
Joined shape going onto merge (677268, 136)
Joined shape after merge (677268, 137)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 137 entries, bv_id to other_staff_costs_th_gbp
dtypes: float64(135), int64(1), object(1)
memory usage: 707.9+ MB
135
Column shape going into merge (7657, 3)
Joined shape going onto merge (677268, 137)
Joined shape after merge (677268, 138)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 138 entries, bv_id to hire_purch._&_leas._(long_t.)_th_gbp
dtypes: float64(136), int64(1), object(1)
memory usage: 713.1+ MB
136
Column shape going into merge (6791, 3)
Joined shape going onto merge (677268, 138)
Joined shape after merge (677268, 139)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 139 entries, bv_id to overseas_turnover_th_gbp
dtypes: float64(137), int64(1), object(1)
memory usage: 718.2+ MB
137
Column shape going into merge (6730, 3)
Joined shape going onto merge (677268, 139)
Joined shape after merge (677268, 140)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 140 entries, bv_id to tax_advice_th_gbp
dtypes: float64(138), int64(1), object(1)
memory usage: 723.4+ MB
138
Column shape going into merge (6440, 3)
Joined shape going onto merge (677268, 140)
Joined shape after merge (677268, 141)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 141 entries, bv_id to directors_loans_(asset)_th_gbp
dtypes: float64(139), int64(1), object(1)
memory usage: 728.6+ MB
139
Column shape going into merge (6005, 3)
Joined shape going onto merge (677268, 141)
Joined shape after merge (677268, 142)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 142 entries, bv_id to finished_goods_th_gbp
dtypes: float64(140), int64(1), object(1)
memory usage: 733.7+ MB
140
Column shape going into merge (5659, 3)
Joined shape going onto merge (677268, 142)
Joined shape after merge (677268, 143)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 143 entries, bv_id to revaluation_reserves_th_gbp
dtypes: float64(141), int64(1), object(1)
memory usage: 738.9+ MB
141
Column shape going into merge (5190, 3)
Joined shape going onto merge (677268, 143)
Joined shape after merge (677268, 144)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 144 entries, bv_id to land_&_building_or_property_rents_&_other_th_gbp
dtypes: float64(142), int64(1), object(1)
memory usage: 744.1+ MB
142
Column shape going into merge (5085, 3)
Joined shape going onto merge (677268, 144)
Joined shape after merge (677268, 145)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 145 entries, bv_id to pension_contribution_th_gbp
dtypes: float64(143), int64(1), object(1)
memory usage: 749.2+ MB
143
Column shape going into merge (5076, 3)
Joined shape going onto merge (677268, 145)
Joined shape after merge (677268, 146)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 146 entries, bv_id to cash_out(in)flow_investing_activ._th_gbp
dtypes: float64(144), int64(1), object(1)
memory usage: 754.4+ MB
144
Column shape going into merge (4943, 3)
Joined shape going onto merge (677268, 146)
Joined shape after merge (677268, 147)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 147 entries, bv_id to w.i.p._th_gbp
dtypes: float64(145), int64(1), object(1)
memory usage: 759.6+ MB
145
Column shape going into merge (4268, 3)
Joined shape going onto merge (677268, 147)
Joined shape after merge (677268, 148)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 148 entries, bv_id to highest_paid_director_th_gbp
dtypes: float64(146), int64(1), object(1)
memory usage: 764.7+ MB
146
Column shape going into merge (4181, 3)
Joined shape going onto merge (677268, 148)
Joined shape after merge (677268, 149)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 149 entries, bv_id to hire_of_plant_&_machinery_th_gbp
dtypes: float64(147), int64(1), object(1)
memory usage: 769.9+ MB
147
Column shape going into merge (3589, 3)
Joined shape going onto merge (677268, 149)
Joined shape after merge (677268, 150)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 150 entries, bv_id to hire_purchase_(short_t.)_th_gbp
dtypes: float64(148), int64(1), object(1)
memory usage: 775.1+ MB
148
Column shape going into merge (2785, 3)
Joined shape going onto merge (677268, 150)

Joined shape after merge (677268, 151)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 151 entries, bv_id to hire_purchase_(long_t.)_th_gbp
dtypes: float64(149), int64(1), object(1)
memory usage: 780.2+ MB
149
Column shape going into merge (2356, 3)
Joined shape going onto merge (677268, 151)
Joined shape after merge (677268, 152)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 152 entries, bv_id to other_emoluments_th_gbp
dtypes: float64(150), int64(1), object(1)
memory usage: 785.4+ MB
150
Column shape going into merge (2345, 3)
Joined shape going onto merge (677268, 152)
Joined shape after merge (677268, 153)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 153 entries, bv_id to leasing_(short_t.)_th_gbp
dtypes: float64(151), int64(1), object(1)
memory usage: 790.6+ MB
151
Column shape going into merge (2201, 3)
Joined shape going onto merge (677268, 153)
Joined shape after merge (677268, 154)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 154 entries, bv_id to paid_on_hire_purchase_th_gbp
dtypes: float64(152), int64(1), object(1)
memory usage: 795.7+ MB
152
Column shape going into merge (1944, 3)
Joined shape going onto merge (677268, 154)
Joined shape after merge (677268, 155)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 155 entries, bv_id to pension_liabilities_th_gbp
dtypes: float64(153), int64(1), object(1)
memory usage: 800.9+ MB
153
Column shape going into merge (1855, 3)
Joined shape going onto merge (677268, 155)
Joined shape after merge (677268, 156)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 156 entries, bv_id to leasing_(long_t.)_th_gbp
dtypes: float64(154), int64(1), object(1)
memory usage: 806.1+ MB
154
Column shape going into merge (1587, 3)
Joined shape going onto merge (677268, 156)
Joined shape after merge (677268, 157)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 157 entries, bv_id to exceptional_items_th_gbp
dtypes: float64(155), int64(1), object(1)
memory usage: 811.2+ MB
155
Column shape going into merge (1169, 3)
Joined shape going onto merge (677268, 157)
Joined shape after merge (677268, 158)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 158 entries, bv_id to exceptional_items_pre_op_th_gbp
dtypes: float64(156), int64(1), object(1)
memory usage: 816.4+ MB
156
Column shape going into merge (1131, 3)
Joined shape going onto merge (677268, 158)
Joined shape after merge (677268, 159)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 159 entries, bv_id to equity_dividends_paid_th_gbp
dtypes: float64(157), int64(1), object(1)
memory usage: 821.6+ MB
157
Column shape going into merge (893, 3)
Joined shape going onto merge (677268, 159)
Joined shape after merge (677268, 160)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 160 entries, bv_id to extraordinary_items_th_gbp
dtypes: float64(158), int64(1), object(1)
memory usage: 826.7+ MB
158
Column shape going into merge (856, 3)
Joined shape going onto merge (677268, 160)
Joined shape after merge (677268, 161)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 161 entries, bv_id to balance_sheet_minorities_th_gbp
dtypes: float64(159), int64(1), object(1)
memory usage: 831.9+ MB
159
Column shape going into merge (836, 3)
Joined shape going onto merge (677268, 161)
Joined shape after merge (677268, 162)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 162 entries, bv_id to other_exceptional_items_th_gbp
dtypes: float64(160), int64(1), object(1)
memory usage: 837.1+ MB
160
Column shape going into merge (821, 3)
Joined shape going onto merge (677268, 162)
Joined shape after merge (677268, 163)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 163 entries, bv_id to minority_interests_th_gbp
dtypes: float64(161), int64(1), object(1)
memory usage: 842.2+ MB
161
Column shape going into merge (777, 3)
Joined shape going onto merge (677268, 163)
Joined shape after merge (677268, 164)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 164 entries, bv_id to profit_(loss)_on_disposal_th_gbp
dtypes: float64(162), int64(1), object(1)
memory usage: 847.4+ MB
162
Column shape going into merge (748, 3)
Joined shape going onto merge (677268, 164)
Joined shape after merge (677268, 165)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 165 entries, bv_id to research_&_development_th_gbp
dtypes: float64(163), int64(1), object(1)
memory usage: 852.6+ MB
163
Column shape going into merge (519, 3)
Joined shape going onto merge (677268, 165)
Joined shape after merge (677268, 166)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 166 entries, bv_id to other_shares_th_gbp
dtypes: float64(164), int64(1), object(1)
memory usage: 857.7+ MB
164
Column shape going into merge (418, 3)
Joined shape going onto merge (677268, 166)
Joined shape after merge (677268, 167)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 167 entries, bv_id to acquisition_&_disposal_th_gbp
dtypes: float64(165), int64(1), object(1)
memory usage: 862.9+ MB
165
Column shape going into merge (406, 3)
Joined shape going onto merge (677268, 167)
Joined shape after merge (677268, 168)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 168 entries, bv_id to impairment_tangibles_th_gbp
dtypes: float64(166), int64(1), object(1)
memory usage: 868.1+ MB
166
Column shape going into merge (400, 3)
Joined shape going onto merge (677268, 168)
Joined shape after merge (677268, 169)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 169 entries, bv_id to paid_on_leasing_th_gbp
dtypes: float64(167), int64(1), object(1)
memory usage: 873.2+ MB
167
Column shape going into merge (397, 3)
Joined shape going onto merge (677268, 169)
Joined shape after merge (677268, 170)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 170 entries, bv_id to impairment_th_gbp
dtypes: float64(168), int64(1), object(1)
memory usage: 878.4+ MB
168
Column shape going into merge (392, 3)
Joined shape going onto merge (677268, 170)
Joined shape after merge (677268, 171)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 171 entries, bv_id to dividends_th_gbp
dtypes: float64(169), int64(1), object(1)
memory usage: 883.6+ MB
169
Column shape going into merge (383, 3)
Joined shape going onto merge (677268, 171)
Joined shape after merge (677268, 172)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 172 entries, bv_id to preference_shares_th_gbp
dtypes: float64(170), int64(1), object(1)
memory usage: 888.7+ MB
170
Column shape going into merge (89, 3)
Joined shape going onto merge (677268, 172)
Joined shape after merge (677268, 173)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 173 entries, bv_id to management_of_liquid_resources_th_gbp
dtypes: float64(171), int64(1), object(1)
memory usage: 893.9+ MB
171
Column shape going into merge (65, 3)
Joined shape going onto merge (677268, 173)
Joined shape after merge (677268, 174)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 174 entries, bv_id to other_income_pre_gp_th_gbp
dtypes: float64(172), int64(1), object(1)
memory usage: 899.1+ MB
172
Column shape going into merge (53, 3)
Joined shape going onto merge (677268, 174)
Joined shape after merge (677268, 175)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 175 entries, bv_id to other_auditors_services_th_gbp
dtypes: float64(173), int64(1), object(1)
memory usage: 904.3+ MB
173
Column shape going into merge (28, 3)
Joined shape going onto merge (677268, 175)

Joined shape after merge (677268, 176)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 176 entries, bv_id to costs_of_reorganisation_th_gbp
dtypes: float64(174), int64(1), object(1)
memory usage: 909.4+ MB
174
Column shape going into merge (17, 3)
Joined shape going onto merge (677268, 176)
Joined shape after merge (677268, 177)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 177 entries, bv_id to non-audit_fees_paid_to_other_auditors_th_gbp
dtypes: float64(175), int64(1), object(1)
memory usage: 914.6+ MB
175
Column shape going into merge (7, 3)
Joined shape going onto merge (677268, 177)
Joined shape after merge (677268, 178)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 178 entries, bv_id to exceptional_items_pre_gp_th_gbp
dtypes: float64(176), int64(1), object(1)
memory usage: 919.8+ MB
176
Column shape going into merge (0, 3)
Joined shape going onto merge (677268, 178)
Joined shape after merge (677268, 179)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677268 entries, 0 to 677267
Columns: 179 entries, bv_id to profit_(loss)_on_sale_of_operations_th_gbp
dtypes: float64(177), int64(1), object(1)
memory usage: 924.9+ MB
177

In [1]:
data = pd.HDFStore('bdv-data.h5')
print(data['flat'].shape)
print(data['gifi'].shape)

NameError: name 'pd' is not defined

In [61]:
gifi = data['gifi']
gifi.head()

                 total_assets_less_cur._liab._th_gbp  net_assets_th_gbp  \
bv_id      year
GB07114772 2011                                0.313              0.313
           2012                                0.313              0.313
           2013                                0.313              0.313
           2014                                0.313              0.313
           2015                                0.313              0.313

                 net_tangible_assets_(liab.)_th_gbp  total_assets_th_gbp  \
bv_id      year
GB07114772 2011                               0.313               24.788
           2012                               0.313                0.313
           2013                               0.313                0.313
           2014                               0.313                0.313
           2015                               0.313                0.313

                 net_current_assets_(working_capital)_th_gbp  \
bv_id      year
GB07114772 2011                                        0.313
           2012                                        0.313
           2013                                        0.313
           2014                                        0.313
           2015                                        0.313

                 shareholders_funds_th_gbp  current_assets_th_gbp  \
bv_id      year
GB07114772 2011                      0.313                 24.788
           2012                      0.313                  0.313
           2013                      0.313                  0.313
           2014                      0.313                  0.313
           2015                      0.313                  0.313

                 total_reserves_th_gbp  current_liabilities_th_gbp  \
bv_id      year
GB07114772 2011                  0.311                     -24.475
           2012                  0.311                         NaN
           2013                  0.311                         NaN
           2014                  0.311                         NaN
           2015                  0.313                         NaN

                 solvency_ratio_(asset_based)_(%)  ...  impairment_th_gbp  \
bv_id      year                                    ...
GB07114772 2011                          1.262708  ...                NaN
           2012                        100.000000  ...                NaN
           2013                        100.000000  ...                NaN
           2014                        100.000000  ...                NaN
           2015                        100.000000  ...                NaN

                 dividends_th_gbp  preference_shares_th_gbp  \
bv_id      year
GB07114772 2011               NaN                       NaN
           2012               NaN                       NaN
           2013               NaN                       NaN
           2014               NaN                       NaN
           2015               NaN                       NaN

                 management_of_liquid_resources_th_gbp  \
bv_id      year
GB07114772 2011                                    NaN
           2012                                    NaN
           2013                                    NaN
           2014                                    NaN
           2015                                    NaN

                 other_income_pre_gp_th_gbp  other_auditors_services_th_gbp  \
bv_id      year
GB07114772 2011                         NaN                             NaN
           2012                         NaN                             NaN
           2013                         NaN                             NaN
           2014                         NaN                             NaN
           2015                         NaN                             NaN

                 costs_of_reorganisation_th_gbp  \
bv_id      year
GB07114772 2011                             NaN
           2012                             NaN
           2013                             NaN
           2014                             NaN
           2015                             NaN

                 non-audit_fees_paid_to_other_auditors_th_gbp  \
bv_id      year
GB07114772 2011                                           NaN
           2012                                           NaN
           2013                                           NaN
           2014                                           NaN
           2015                                           NaN

                 exceptional_items_pre_gp_th_gbp  \
bv_id      year
GB07114772 2011                              NaN
           2012                              NaN
           2013                              NaN
           2014                              NaN
           2015                              NaN

                 profit_(loss)_on_sale_of_operations_th_gbp
bv_id      year
GB07114772 2011                                         NaN
           2012                                         NaN
           2013                                         NaN
           2014                                         NaN
           2015                                         NaN

[5 rows x 177 columns]

In [49]:
gifi.describe()

,year,total_assets_less_cur._liab._th_gbp,net_assets_th_gbp,net_tangible_assets_(liab.)_th_gbp,total_assets_th_gbp,net_current_assets_(working_capital)_th_gbp,shareholders_funds_th_gbp,current_assets_th_gbp,total_reserves_th_gbp,current_liabilities_th_gbp,...,impairment_th_gbp,dividends_th_gbp,preference_shares_th_gbp,management_of_liquid_resources_th_gbp,other_income_pre_gp_th_gbp,other_auditors_services_th_gbp,costs_of_reorganisation_th_gbp,non-audit_fees_paid_to_other_auditors_th_gbp,exceptional_items_pre_gp_th_gbp,profit_(loss)_on_sale_of_operations_th_gbp
count,677268.000000,6.724450e+05,6.695380e+05,6.683810e+05,6.640230e+05,6.593410e+05,6.541590e+05,6.433600e+05,6.029620e+05,5.670010e+05,...,397.000000,392.000000,383.000000,89.000000,65.000000,53.000000,28.000000,17.000000,7.000000,0.0
mean,2015.685222,1.260332e+03,7.295762e+01,1.208804e+03,2.366745e+03,-1.364575e+02,1.072910e+02,9.856020e+02,-1.384286e+00,-1.277015e+03,...,2473.361972,-89.451011,-8621.353449,-2873.447562,656.081246,2.837830,-4374.667750,2.782647,158.791143,NaN
std,2.160796,3.703311e+04,1.709831e+04,3.699529e+04,5.483618e+04,3.854080e+04,1.717469e+04,2.265413e+04,1.598404e+04,4.178649e+04,...,12080.914992,371.935440,29792.272221,16159.320911,4966.853690,4.141245,24117.381117,4.413339,350.181648,NaN
min,2011.000000,-5.051191e+06,-5.051191e+06,-5.051191e+06,7.118587e-04,-1.418032e+07,-5.051191e+06,7.049503e-04,-5.164004e+06,-1.494471e+07,...,-2.000000,-4809.000000,-299866.355000,-78407.000000,-3220.000000,0.100000,-127410.000000,0.215000,-228.025000,NaN
25%,2014.000000,1.000000e-03,-1.908000e+00,1.000000e-03,3.351000e+00,-4.070000e+00,-2.166000e+00,2.519000e+00,-4.030750e+00,-7.656969e+01,...,35.000000,-40.000000,-5342.978000,-293.000000,0.010000,0.600000,-1.805250,0.517000,-23.136000,NaN
50%,2016.000000,1.548000e+00,2.960000e-01,1.416000e+00,1.619800e+01,1.920000e-01,3.670000e-01,1.220100e+01,4.860000e-01,-1.602300e+01,...,190.631000,-13.575000,-1301.167000,-0.010000,0.244000,1.458000,17.073500,1.200000,6.879000,NaN
75%,2017.000000,1.704500e+01,5.987000e+00,1.592683e+01,8.584200e+01,6.949000e+00,6.354000e+00,5.775000e+01,6.936000e+00,-4.299000e+00,...,1060.676000,-5.000000,-196.819000,145.352000,6.250000,3.210000,91.010000,2.622000,294.193500,NaN
max,2019.000000,1.585428e+07,3.357354e+06,1.585386e+07,1.586550e+07,1.160269e+07,3.357354e+06,1.160837e+07,3.357353e+06,-7.049503e-04,...,181326.000000,-0.001000,-0.001000,34948.000000,39769.695000,26.378000,2346.000000,16.823000,790.569000,NaN